import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname.replace(/\/$/,'');const {default:worker,parseHL7}=await import(root+'/worker/api.js');
const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')))db.exec(fs.readFileSync(root+'/drizzle/'+file,'utf8'));
const env={KNOX_OWNER_EMAIL:'owner@example.com',DB:{prepare(sql){return {bind(...args){const s=db.prepare(sql);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)}}}}},async batch(queries){db.exec('BEGIN');try{const r=[];for(const q of queries)r.push(await q.run());db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}}};
env.KNOX_OWNER_PASSWORD_HASH=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test-password')))].map(x=>x.toString(16).padStart(2,'0')).join('');
async function call(path,method='GET',data,email='owner@example.com',headers={}){const h={'content-type':'application/json',...headers};if(email){h['x-knox-username']=email;h['x-knox-password']='test-password'}const res=await worker.fetch(new Request('https://knox.test'+path,{method,headers:h,body:data?JSON.stringify(data):undefined}),env);return {status:res.status,data:await res.json()}}
assert.equal((await call('/api/state','GET',null,null)).status,401);assert.equal((await call('/api/state','GET',null,'unknown@example.com')).status,403);
assert.equal((await call('/api/me')).data.user.role,'admin');
for(const role of ['viewer','reception','scientist'])assert.equal((await call('/api/staff','POST',{name:role,email:role+'@example.com',role,password:'test-password'})).status,200);
assert.equal((await call('/api/staff','POST',{email:'owner@example.com',name:'owner',role:'viewer'})).status,400);
let s=(await call('/api/state')).data;assert.equal(s.revision,0);
assert.equal((await call('/api/state','PUT',s,'viewer@example.com')).status,403);
s.data.patients.push({id:'P1',name:'Test patient',dob:'1990-01-01',sex:'Male'});s.data.orders.push({id:'KDX1',patient:'P1',received:true,reviewed:false,testId:'RBS',template:{fields:[{name:'Glucose',unit:'mmol/L',type:'number'}]}});
let saved=await call('/api/state','PUT',s);assert.equal(saved.status,200);assert.equal((await call('/api/state','PUT',s)).status,409);s=saved.data;
let bad=structuredClone(s);bad.data.orders[0].result='5';assert.equal((await call('/api/state','PUT',bad,'reception@example.com')).status,403);
assert.equal((await call('/api/interfaces','POST',{name:'Mindray',model:'BS-240 test',protocol:'JSON',mapping:{GLU:{testId:'RBS',parameter:'Glucose',unit:'mmol/L'}}},'scientist@example.com')).status,403);
const i=(await call('/api/interfaces','POST',{name:'Mindray',model:'BS-240 test',protocol:'JSON',mapping:{GLU:{testId:'RBS',parameter:'Glucose',unit:'mmol/L'}}})).data;
const msg={messageId:'M1',sampleId:'KDX1',results:[{code:'GLU',value:'5.2',unit:'mmol/L'}]};const endpoint='/api/mindray/'+i.id+'/messages';assert.equal((await call(endpoint,'POST',msg,null)).status,401);
let got=await call(endpoint,'POST',msg,null,{authorization:'Bearer '+i.token});assert.equal(got.status,202);const mid=got.data.id;
assert.equal((await call(endpoint,'POST',msg,null,{authorization:'Bearer '+i.token})).data.duplicate,true);assert.equal((await call(endpoint,'POST',{...msg,sampleId:'different'},null,{authorization:'Bearer '+i.token})).status,409);
let imported=await call('/api/messages/'+mid+'/apply','POST',{orderId:'KDX1',revision:s.revision},'scientist@example.com');assert.equal(imported.status,200,JSON.stringify(imported));assert.equal(imported.data.data.orders[0].resultRows[0].value,'5.2');assert.equal(imported.data.data.orders[0].reviewed,false);assert.equal((await call('/api/messages')).data.messages[0].status,'imported');
let state=imported.data;state.data.orders[0].reviewed=true;state.data.orders[0].specimen='Serum';state.data.orders[0].clinicalReview={identity:true,qc:true,references:true,evidence:'Validation test SOP / QC 1'};state.data.orders[0].resultRows[0].reference='Test-only interval';state.data.orders[0].reviewer='forged';let reviewed=await call('/api/state','PUT',state,'scientist@example.com');assert.equal(reviewed.status,200);assert.equal(reviewed.data.data.orders[0].reviewer,'scientist');state=reviewed.data;state.data.orders[0].result='changed';assert.equal((await call('/api/state','PUT',state,'scientist@example.com')).status,403);
assert.equal((await call('/api/staff','POST',{name:'scientist',email:'scientist@example.com',role:'scientist',active:false})).status,200);assert.equal((await call('/api/state','GET',null,'scientist@example.com')).status,403);
assert.equal((await call('/api/state','PUT',state,'owner@example.com',{origin:'https://evil.test'})).status,403);
const raw='MSH|^~\\&|MINDRAY||||||ORU^R01|MSG1|P|2.3.1\rOBR|1||KDX1\rOBX|1|NM|GLU||5.2|mmol/L|||||F\r';assert.equal(parseHL7(raw).sampleId,'KDX1');assert.equal(parseHL7(raw).results[0].value,'5.2');
assert.throws(()=>parseHL7(raw+'OBR|2||KDX2\r'));
console.log('PASS: owner provisioning, unauthorized access, staff creation/disable, role enforcement, CSRF, revision conflicts, token auth, idempotency, sample matching, mapped draft import, review attribution, reviewed-result protection, HL7 parsing and profile rejection');
const {validateRelease}=await import(root+'/worker/api.js');
const clinical={patient:'P1',received:true,specimen:'Serum',method:'Validated method',template:{fields:[{name:'Glucose',type:'number'}]},resultRows:[{name:'Glucose',type:'number',value:'5.2',unit:'mmol/L',reference:'Locally approved test interval',state:'Result'}],clinicalReview:{identity:true,qc:true,references:true,evidence:'SOP/QC'}};
const clinicalData={patients:[{id:'P1',name:'Test',dob:'1990-01-01',sex:'Male'}]};
validateRelease(clinical,clinicalData);
for(const mutate of [o=>o.received=false,o=>o.resultRows[0].value='',o=>o.resultRows[0].reference='PROVISIONAL',o=>o.clinicalReview.qc=false,o=>o.resultRows[0].flag='Critical']){const x=structuredClone(clinical);mutate(x);assert.throws(()=>validateRelease(x,clinicalData));}
assert.equal((await call('/api/me','GET',null,null,{'oai-authenticated-user-id':'x','oai-authenticated-user-email':'owner@example.com'})).status,401);
assert.equal((await call('/api/me')).data.user.name,'IT ADMIN');
console.log('PASS: release rejects incomplete results, provisional ranges, unchecked QC, unreceived samples and undocumented critical results; passwordless platform identity rejected; IT ADMIN display name');
// Legacy reviewed orders lack patientId and may predate release documentation.
let legacy=(await call('/api/state')).data;
legacy.data.orders.push({id:'LEGACY1',patient:'P1',reviewed:true,result:'Historical result',reviewer:'Original reviewer'});
db.prepare('UPDATE workspace SET data=? WHERE id=1').run(JSON.stringify(legacy.data));
let registration=(await call('/api/state')).data;
registration.data.patients.push({id:'P2',name:'Registration regression',sex:'Female',dob:'1995-01-01'});
const registrationSaved=await call('/api/state','PUT',registration);
assert.equal(registrationSaved.status,200,JSON.stringify(registrationSaved.data));
assert.equal(registrationSaved.data.data.orders.find(o=>o.id==='LEGACY1').reviewer,'Original reviewer');
const invalidEdit=structuredClone(registrationSaved.data);invalidEdit.data.orders.find(o=>o.id==='LEGACY1').result='Changed result';
assert.equal((await call('/api/state','PUT',invalidEdit)).status,422);
console.log('PASS: patient registration alongside legacy reviewed results; reviewer preserved; changed results still validated');
// Administrator-defined activities override the broad profile, including viewer profiles.
assert.equal((await call('/api/staff','POST',{email:'limited@example.com',name:'Limited registrar',position:'Registration officer',role:'viewer',password:'test-password',permissions:['patients']})).status,200);
const limited=(await call('/api/me','GET',null,'limited@example.com')).data.user;
assert.equal(limited.position,'Registration officer');assert.deepEqual(limited.permissions,['patients']);
let restricted=(await call('/api/state')).data;restricted.data.patients.push({id:'P3',name:'Permission test'});
assert.equal((await call('/api/state','PUT',restricted,'limited@example.com')).status,200);
restricted=(await call('/api/state')).data;restricted.data.sales.push({id:'S1',patient:'P3',total:10});
assert.equal((await call('/api/state','PUT',restricted,'limited@example.com')).status,403);
assert.equal((await call('/api/staff','POST',{email:'limited@example.com',name:'Escalation',role:'admin'},'limited@example.com')).status,403);
assert.equal((await call('/api/staff','POST',{email:'limited@example.com',name:'Limited registrar',role:'viewer',permissions:['invalid']})).status,400);
assert.equal((await call('/api/staff','POST',{email:'limited@example.com',name:'Limited registrar',role:'viewer',permissions:[]})).status,200);
restricted=(await call('/api/state')).data;restricted.data.patients.push({id:'P4',name:'Revocation test'});
assert.equal((await call('/api/state','PUT',restricted,'limited@example.com')).status,403);
console.log('PASS: custom position, individual permissions, denied finance, blocked privilege escalation, invalid permissions and immediate revocation');
const emailState=(await call('/api/state')).data;
assert.equal((await call('/api/results/email-draft','POST',{orderId:'KDX1',recipient:'recipient@example.com',revision:emailState.revision},'limited@example.com')).status,403);
const draft=await call('/api/results/email-draft','POST',{orderId:'KDX1',recipient:'recipient@example.com',revision:emailState.revision});assert.equal(draft.status,200);assert.match(draft.data.eml,/X-Unsent: 1/);
assert.equal((await call('/api/results/email-draft','POST',{orderId:'KDX1',recipient:'recipient@example.com',revision:-1})).status,409);
console.log('PASS: email preparation permission, validated report attachment and stale revision rejection');
// Attendance is durable, permission-scoped, date-filtered and safe to retry with the same ID.
const attendanceDay=new Date(Date.now()-86400000).toISOString().slice(0,10),arrivalAt=attendanceDay+'T08:35:00.000Z';
const arrival={id:crypto.randomUUID(),name:'Attendance test staff',arrivalAt};
assert.equal((await call('/api/attendance','POST',arrival,null)).status,401);
assert.equal((await call('/api/attendance','POST',arrival,'viewer@example.com')).status,403);
assert.equal((await call('/api/attendance','GET',null,'viewer@example.com')).status,403);
assert.equal((await call('/api/attendance','POST',{...arrival,name:' '})).status,400);
assert.equal((await call('/api/attendance','POST',{...arrival,arrivalAt:'2026-02-31T08:00:00Z'})).status,400);
assert.equal((await call('/api/attendance','POST',{...arrival,arrivalAt:new Date(Date.now()+3600000).toISOString()})).status,400);
const attendanceSaved=await call('/api/attendance','POST',arrival);assert.equal(attendanceSaved.status,200,JSON.stringify(attendanceSaved.data));
assert.equal(attendanceSaved.data.entry.recorded_by,'owner@example.com');
assert.equal((await call('/api/attendance','POST',arrival)).status,200);
assert.equal((await call('/api/attendance','POST',{...arrival,name:'Different staff'})).status,409);
let arrivals=(await call('/api/attendance?date='+attendanceDay)).data;assert.equal(arrivals.entries.length,1);assert.equal(arrivals.entries[0].staff_name,arrival.name);assert.equal(arrivals.entries[0].arrival_at,arrivalAt);assert(arrivals.names.includes(arrival.name));
assert.equal((await call('/api/attendance?date=2026-02-31')).status,400);
assert.equal((await call('/api/attendance?date='+new Date().toISOString().slice(0,10))).data.entries.length,0);
assert.equal((await call('/api/staff','POST',{name:'reception',email:'reception@example.com',role:'reception',permissions:['attendance']})).status,200);
assert.equal((await call('/api/attendance','POST',{...arrival,id:crypto.randomUUID(),arrivalAt:attendanceDay+'T09:00:00.000Z'},'reception@example.com')).status,200);
arrivals=(await call('/api/attendance?date='+attendanceDay,'GET',null,'reception@example.com')).data;assert.equal(arrivals.entries.length,2);assert.equal(arrivals.entries[0].arrival_at,attendanceDay+'T09:00:00.000Z');
console.log('PASS: attendance saved with staff name/time; date filtering, chronological order, access controls, validation and duplicate-safe retries');
assert.equal((await call('/api/staff','POST',{name:'Finance officer',email:'finance@example.com',role:'reception',position:'Finance officer',password:'test-password',permissions:['finance','orders','specimens','results','review','amend','importResults']})).status,200);
let financeState=(await call('/api/state')).data;
financeState.data.orders.push({id:'FINANCE_ORDER_DENIED',patient:'P1',test:'Test',received:false,reviewed:false});
assert.equal((await call('/api/state','PUT',financeState,'finance@example.com')).status,403);
financeState=(await call('/api/state')).data;
financeState.data.sales.push({id:'FINANCE_RECEIPT',patient:'P1',test:'Test sale',quantity:1,unitPrice:20,total:20,status:'Paid',created:new Date().toISOString()});
assert.equal((await call('/api/state','PUT',financeState,'finance@example.com')).status,200);
console.log('PASS: finance position denies laboratory order writes even with legacy grants and allows receipt recording');
// Revenue history is executive-only; receipt entry stays available to Finance.
assert.equal((await call('/api/staff','POST',{name:'CEO',email:'ceo@example.com',role:'ceo',position:'CEO',password:'test-password'})).status,200);
for(const email of ['viewer@example.com','finance@example.com','reception@example.com']){
 const hidden=(await call('/api/state','GET',null,email)).data;assert.deepEqual(hidden.data.sales,[]);
 assert.equal((await call('/api/state?collection=sales','GET',null,email)).status,403);
 assert.equal((await call('/api/state/read','POST',{collection:'sales'},email)).status,403);
 assert.equal(Object.hasOwn((await call('/api/summary','GET',null,email)).data,'finance'),false);
}
assert((await call('/api/state','GET',null,'ceo@example.com')).data.data.sales.some(s=>s.id==='FINANCE_RECEIPT'));
let receiptState=(await call('/api/state')).data;receiptState.data.orders.push({id:'PRIVATE_ORDER',patient:'P1',test:'Test',received:false,reviewed:false});
assert.equal((await call('/api/state','PUT',receiptState)).status,200);
receiptState=(await call('/api/state','GET',null,'finance@example.com')).data;
receiptState.data.sales.push({id:'PRIVATE_RECEIPT',orderId:'PRIVATE_ORDER',patient:'P1',quantity:1,unitPrice:30,total:30,status:'Paid'});
const recordedReceipt=await call('/api/state','PUT',receiptState,'finance@example.com');assert.equal(recordedReceipt.status,200);assert.deepEqual(recordedReceipt.data.data.sales,[]);
const context=await call('/api/receipt-context','POST',{orderId:'PRIVATE_ORDER'},'finance@example.com');assert.equal(context.status,200);assert.deepEqual(context.data.data.sales.map(s=>s.id),['PRIVATE_RECEIPT']);
assert.equal((await call('/api/receipt-context','POST',{orderId:'PRIVATE_ORDER'},'viewer@example.com')).status,403);
assert((await call('/api/state')).data.data.sales.some(s=>s.id==='FINANCE_RECEIPT'));
console.log('PASS: CEO/admin sales history; staff state/summary/history restrictions; private receipt entry and request-scoped receipt access; hidden sales preserved');
// Dedicated ultrasound permissions, authenticated finalisation and history preservation.
for(const [email,permissions] of [['sonographer@example.com',['ultrasoundView','ultrasoundEnter']],['scan-approver@example.com',['ultrasoundView','ultrasoundReview']],['scan-amender@example.com',['ultrasoundView','ultrasoundEnter','ultrasoundReview','ultrasoundAmend']]])assert.equal((await call('/api/staff','POST',{email,name:email,role:'viewer',position:'Sonographer',password:'test-password',permissions})).status,200);
let us=(await call('/api/state','GET',null,'sonographer@example.com')).data;
us.data.ultrasoundReports.push({id:'US1',patient:'P1',test:'Abdominal ultrasound',department:'Ultrasound',examAt:'2025-10-01T10:00:00Z',created:'2025-10-01T09:00:00Z',operator:'Sonographer',technique:'Transabdominal',indication:'Test',impression:'Initial impression',template:{fields:[{name:'Finding',type:'narrative'}]},resultRows:[{name:'Finding',value:'Test finding',state:'Result'}],reviewed:false});
assert.equal((await call('/api/state','PUT',us,'sonographer@example.com')).status,200);
assert.deepEqual((await call('/api/state','GET',null,'viewer@example.com')).data.data.ultrasoundReports,[]);
assert.equal((await call('/api/state?collection=ultrasoundReports','GET',null,'viewer@example.com')).status,403);
us=(await call('/api/state','GET',null,'sonographer@example.com')).data;Object.assign(us.data.ultrasoundReports[0],{reviewed:true,identityVerified:true});assert.equal((await call('/api/state','PUT',us,'sonographer@example.com')).status,403);
us=(await call('/api/state','GET',null,'scan-approver@example.com')).data;Object.assign(us.data.ultrasoundReports[0],{reviewed:true,identityVerified:true,reviewer:'Forged reviewer'});
let usApproved=await call('/api/state','PUT',us,'scan-approver@example.com');assert.equal(usApproved.status,200,JSON.stringify(usApproved.data));assert.equal(usApproved.data.data.ultrasoundReports[0].reviewer,'scan-approver@example.com');
us=(await call('/api/state','GET',null,'scan-amender@example.com')).data;us.data.ultrasoundReports[0].impression='Corrected impression';assert.equal((await call('/api/state','PUT',us,'scan-amender@example.com')).status,422);
us.data.ultrasoundReports[0].amendmentReason='Transcription correction';const amendedScan=await call('/api/state','PUT',us,'scan-amender@example.com');assert.equal(amendedScan.status,200);assert.equal(amendedScan.data.data.ultrasoundReports[0].amendments[0].previous.impression,'Initial impression');
const clinicalSave=(await call('/api/state','GET',null,'finance@example.com')).data;clinicalSave.data.sales.push({id:'AFTER_US_RECEIPT',patient:'P1',quantity:1,unitPrice:5,total:5,status:'Paid'});assert.equal((await call('/api/state','PUT',clinicalSave,'finance@example.com')).status,200);assert.equal((await call('/api/state')).data.data.ultrasoundReports.length,1);
console.log('PASS: ultrasound view/entry/review/amend privileges, private records, authenticated approval, amendment reason/history and preservation during other staff saves');
// Brand-neutral interfaces, automatic protocol setup and measured readiness.
const d=(await call('/api/interfaces','POST',{name:'Sysmex QA device',model:'Synthetic model',protocol:'AUTO',device:{brand:'Sysmex',firmware:'QA1',serial:'QA-001'},mapping:{HGB:{testId:'CBC',parameter:'Hemoglobin',unit:'g/dL'}}})).data;
const dh={authorization:'Bearer '+d.token},dp='/api/devices/'+d.id;
assert.equal(d.endpoint,dp+'/messages');
assert.equal((await call(dp+'/configuration','GET',null,null)).status,401);
assert.equal((await call(dp+'/connect','POST',{format:'json',model:'Wrong model'},null,dh)).status,422);
assert.equal((await call(dp+'/messages','POST',{messageId:'invalid'},null,dh)).status,400);
assert.equal((await call(dp+'/configuration','GET',null,null,dh)).data.protocol,'AUTO');
let dc=await call(dp+'/connect','POST',{format:'json',model:'Synthetic model'},null,dh);
assert.equal(dc.status,200);assert.equal(dc.data.protocol,'JSON');assert.equal(dc.data.ready,false);assert.equal(dc.data.status,'Awaiting test message');assert.equal(dc.data.device.brand,'Sysmex');
const dm={messageId:'DEVICE-QA1',sampleId:'QA-SAMPLE',results:[{code:'HGB',value:'13',unit:'g/dL'}]};
let da=await call(dp+'/messages','POST',dm,null,dh);assert.equal(da.status,202);assert.equal(da.data.configuration.ready,true);assert.equal(da.data.status,'pending_review');
assert.equal((await call(dp+'/configuration','GET',null,null,dh)).data.ready,true);
assert.equal((await call(dp+'/messages','POST',dm,null,dh)).data.duplicate,true);
assert.equal((await call(dp+'/messages','POST',{format:'hl7',raw},null,dh)).status,422);
const units=await call(dp+'/messages','POST',{...dm,messageId:'DEVICE-QA2',results:[{code:'HGB',value:'130',unit:'g/L'}]},null,dh);assert.equal(units.status,202);assert.equal(units.data.configuration.ready,false);assert.deepEqual(units.data.configuration.unmappedCodes,['HGB']);
const listed=(await call('/api/interfaces')).data;assert.ok(listed.brands.includes('Abbott'));assert.equal(listed.interfaces.find(x=>x.id===d.id).status,'Mapping required');assert.equal(listed.interfaces.find(x=>x.id===d.id).token,undefined);
const rotated=await call('/api/interfaces','POST',{id:d.id,name:'Disabled QA',model:'Synthetic model',protocol:'AUTO',active:false,mapping:{},device:{brand:'Sysmex'}});assert.equal(rotated.status,200);assert.equal((await call(dp+'/configuration','GET',null,null,dh)).status,401);assert.equal((await call(dp+'/connect','POST',{format:'json'},null,{authorization:'Bearer '+rotated.data.token})).status,401);
const h=(await call('/api/interfaces','POST',{name:'Roche QA device',model:'Synthetic HL7 model',protocol:'AUTO',device:{brand:'Roche'},mapping:{GLU:{testId:'RBS',parameter:'Glucose',unit:'mmol/L'}}})).data;
const ha=await call(h.endpoint,'POST',{format:'hl7',raw},null,{authorization:'Bearer '+h.token});assert.equal(ha.status,202);assert.equal(ha.data.configuration.protocol,'HL7');assert.equal(ha.data.configuration.ready,true);
console.log('PASS: multi-brand configuration, authenticated handshake, JSON/HL7 auto detection, legacy routes, exact-unit readiness, safe draft inbox, disabled devices and key rotation');
