import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname.replace(/\/$/,'');const {default:worker,parseHL7}=await import(root+'/worker/api.js');
import {postgres} from '../worker/postgres.js';
const db=null;
const chunks=[];for await(const chunk of process.stdin)chunks.push(chunk);
const pg=postgres(Buffer.concat(chunks).toString().trim());
const env={KNOX_OWNER_EMAIL:'owner@example.com',DB:pg};
env.KNOX_OWNER_PASSWORD_HASH=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test-password')))].map(x=>x.toString(16).padStart(2,'0')).join('');
async function call(path,method='GET',data,email='owner@example.com',headers={}){const h={'content-type':'application/json',...headers};if(email){h['x-knox-username']=email;h['x-knox-password']='test-password'}const res=await worker.fetch(new Request('https://knox.test'+path,{method,headers:h,body:data?JSON.stringify(data):undefined}),env);return {status:res.status,data:await res.json()}}
assert.equal((await call('/api/state','GET',null,null)).status,401);assert.equal((await call('/api/state','GET',null,'unknown@example.com')).status,403);
assert.equal((await call('/api/me')).data.user.role,'admin');
for(const role of ['viewer','reception','scientist'])assert.equal((await call('/api/staff','POST',{name:role,email:role+'@example.com',role,password:'test-password'})).status,200);
assert.equal((await call('/api/staff','POST',{email:'owner@example.com',name:'owner',role:'viewer'})).status,400);
let s=(await call('/api/state')).data;assert.equal(s.revision,0);
assert.equal((await call('/api/state','PUT',s,'viewer@example.com')).status,403);
s.data.patients.push({id:'P1',name:'Test patient',dob:'1990-01-01',sex:'Male'});s.data.orders.push({id:'KDX1',patient:'P1',received:true,reviewed:false,testId:'RBS',template:{fields:[{name:'Glucose',unit:'mmol/L',type:'number'}]}});
let saved=await call('/api/state','PUT',s);assert.equal(saved.status,200);assert.equal((await call('/api/state','PUT',s)).status,409);s=saved.data;
let bad=structuredClone(s);bad.data.orders[0].result='5';assert.equal((await call('/api/state','PUT',bad,'reception@example.com')).status,403);
assert.equal((await call('/api/interfaces','POST',{name:'Mindray',model:'BS-240 test',protocol:'JSON',mapping:{GLU:{testId:'RBS',parameter:'Glucose',unit:'mmol/L'}}},'scientist@example.com')).status,403);
const i=(await call('/api/interfaces','POST',{name:'Mindray',model:'BS-240 test',protocol:'JSON',mapping:{GLU:{testId:'RBS',parameter:'Glucose',unit:'mmol/L'}}})).data;
const msg={messageId:'M1',sampleId:'KDX1',results:[{code:'GLU',value:'5.2',unit:'mmol/L'}]};const endpoint='/api/mindray/'+i.id+'/messages';assert.equal((await call(endpoint,'POST',msg,null)).status,401);
let got=await call(endpoint,'POST',msg,null,{authorization:'Bearer '+i.token});assert.equal(got.status,202);const mid=got.data.id;
assert.equal((await call(endpoint,'POST',msg,null,{authorization:'Bearer '+i.token})).data.duplicate,true);assert.equal((await call(endpoint,'POST',{...msg,sampleId:'different'},null,{authorization:'Bearer '+i.token})).status,409);
let imported=await call('/api/messages/'+mid+'/apply','POST',{orderId:'KDX1',revision:s.revision},'scientist@example.com');assert.equal(imported.status,200,JSON.stringify(imported));assert.equal(imported.data.data.orders[0].resultRows[0].value,'5.2');assert.equal(imported.data.data.orders[0].reviewed,false);assert.equal((await call('/api/messages')).data.messages[0].status,'imported');
let state=imported.data;state.data.orders[0].reviewed=true;state.data.orders[0].specimen='Serum';state.data.orders[0].clinicalReview={identity:true,qc:true,references:true,evidence:'Validation test SOP / QC 1'};state.data.orders[0].resultRows[0].reference='Test-only interval';state.data.orders[0].reviewer='forged';let reviewed=await call('/api/state','PUT',state,'scientist@example.com');assert.equal(reviewed.status,200);assert.equal(reviewed.data.data.orders[0].reviewer,'scientist');state=reviewed.data;state.data.orders[0].result='changed';assert.equal((await call('/api/state','PUT',state,'scientist@example.com')).status,403);
assert.equal((await call('/api/staff','POST',{name:'scientist',email:'scientist@example.com',role:'scientist',active:false})).status,200);assert.equal((await call('/api/state','GET',null,'scientist@example.com')).status,403);
assert.equal((await call('/api/state','PUT',state,'owner@example.com',{origin:'https://evil.test'})).status,403);
const raw='MSH|^~\\&|MINDRAY||||||ORU^R01|MSG1|P|2.3.1\rOBR|1||KDX1\rOBX|1|NM|GLU||5.2|mmol/L|||||F\r';assert.equal(parseHL7(raw).sampleId,'KDX1');assert.equal(parseHL7(raw).results[0].value,'5.2');
assert.throws(()=>parseHL7(raw+'OBR|2||KDX2\r'));
console.log('PASS: owner provisioning, unauthorized access, staff creation/disable, role enforcement, CSRF, revision conflicts, token auth, idempotency, sample matching, mapped draft import, review attribution, reviewed-result protection, HL7 parsing and profile rejection');
const {validateRelease}=await import(root+'/worker/api.js');
const clinical={patient:'P1',received:true,specimen:'Serum',method:'Validated method',template:{fields:[{name:'Glucose',type:'number'}]},resultRows:[{name:'Glucose',type:'number',value:'5.2',unit:'mmol/L',reference:'Locally approved test interval',state:'Result'}],clinicalReview:{identity:true,qc:true,references:true,evidence:'SOP/QC'}};
const clinicalData={patients:[{id:'P1',name:'Test',dob:'1990-01-01',sex:'Male'}]};
validateRelease(clinical,clinicalData);
for(const mutate of [o=>o.received=false,o=>o.resultRows[0].value='',o=>o.resultRows[0].reference='PROVISIONAL',o=>o.clinicalReview.qc=false,o=>o.resultRows[0].flag='Critical']){const x=structuredClone(clinical);mutate(x);assert.throws(()=>validateRelease(x,clinicalData));}
assert.equal((await call('/api/me','GET',null,null,{'oai-authenticated-user-id':'x','oai-authenticated-user-email':'owner@example.com'})).status,401);
assert.equal((await call('/api/me')).data.user.name,'Admin (Administrator)');
console.log('PASS: release rejects incomplete results, provisional ranges, unchecked QC, unreceived samples and undocumented critical results; passwordless platform identity rejected; Admin (Administrator) display name');
// Legacy reviewed orders lack patientId and may predate release documentation.
let legacy=(await call('/api/state')).data;
legacy.data.orders.push({id:'LEGACY1',patient:'P1',reviewed:true,result:'Historical result',reviewer:'Original reviewer'});
await pg.prepare('UPDATE workspace SET data=? WHERE id=1').bind(JSON.stringify(legacy.data)).run();
let registration=(await call('/api/state')).data;
registration.data.patients.push({id:'P2',name:'Registration regression',sex:'Female',dob:'1995-01-01'});
const registrationSaved=await call('/api/state','PUT',registration);
assert.equal(registrationSaved.status,200,JSON.stringify(registrationSaved.data));
assert.equal(registrationSaved.data.data.orders.find(o=>o.id==='LEGACY1').reviewer,'Original reviewer');
const invalidEdit=structuredClone(registrationSaved.data);invalidEdit.data.orders.find(o=>o.id==='LEGACY1').result='Changed result';
assert.equal((await call('/api/state','PUT',invalidEdit)).status,422);
console.log('PASS: patient registration alongside legacy reviewed results; reviewer preserved; changed results still validated');
