import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import worker from '../worker/api.js';
import {recordChangeEvents} from '../worker/change-audit.js';
test('server requires delete and amendment reasons and captures trusted before/after details without binary attachments',()=>{const old={orders:[{id:'O',reviewed:true,result:'5',signature:'data:image/png;base64,SECRET',attachments:[{name:'trace',data:'SECRET'}]}]},next={orders:[{...old.orders[0],result:'6',changeReason:'Transcription correction'}]};assert.throws(()=>recordChangeEvents(old,{orders:[]},{email:'staff',name:'Staff'}));const events=recordChangeEvents(old,next,{email:'real@example.com',name:'Actual Staff'});assert.equal(events[0].operation,'Amended');assert.equal(events[0].before.result,'5');assert.equal(events[0].after.result,'6');assert.equal(events[0].staffEmail,'real@example.com');assert(!JSON.stringify(events).includes('SECRET'));});
test('deletions require reasons, logs are admin-only and an audit failure rolls the deletion back atomically',async()=>{const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const env={KNOX_OWNER_EMAIL:'owner@example.com',KNOX_OWNER_PASSWORD_HASH:Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test-password'))).toString('hex'),DB:{prepare(sql){return {bind(...args){return {async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return db.prepare(sql).run(...args)}}}}},async batch(commands){db.exec('BEGIN');try{const out=[];for(const c of commands)out.push(await c.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}}};
async function call(path,method='GET',data,email='owner@example.com'){const r=await worker.fetch(new Request('https://test'+path,{method,headers:{'content-type':'application/json','x-knox-username':email,'x-knox-password':'test-password'},body:data?JSON.stringify(data):undefined}),env);return {status:r.status,body:await r.json()}}
let state=(await call('/api/state')).body;state.data.patients.push({id:'P1',name:'Test patient',dob:'1990-01-01',sex:'Female'});state=(await call('/api/state','PUT',state)).body;
const deletion=structuredClone(state);deletion.data.patients=[];assert.equal((await call('/api/state','PUT',deletion)).status,422);assert.equal((await call('/api/state')).body.revision,state.revision);
deletion.changeReasons={'patients:P1':'Duplicate registration'};db.exec("CREATE TRIGGER audit_failure BEFORE INSERT ON audit WHEN NEW.action LIKE '%record-change%' BEGIN SELECT RAISE(ABORT,'audit fixture failure'); END;");assert.notEqual((await call('/api/state','PUT',deletion)).status,200);assert.equal((await call('/api/state')).body.data.patients.length,1);assert.equal((await call('/api/state')).body.revision,state.revision);db.exec('DROP TRIGGER audit_failure');assert.equal((await call('/api/state','PUT',deletion)).status,200);
const audit=(await call('/api/audit')).body.events.map(e=>{try{return JSON.parse(e.action)}catch{return null}}).find(e=>e?.operation==='Deleted');assert.equal(audit.reason,'Duplicate registration');assert.equal(audit.before.name,'Test patient');assert.equal(audit.after,null);assert.equal(audit.staffEmail,'owner@example.com');assert.equal((await call('/api/staff','POST',{email:'staff@example.com',name:'Staff',role:'scientist',password:'test-password',permissions:['audit']})).status,200);assert.equal((await call('/api/audit','GET',null,'staff@example.com')).status,403);db.close();});
