import {patientAge} from './patient-age.js';
const reportEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const reportText=v=>reportEscape(v||'Not recorded');
const reportTime=v=>{if(!v)return 'Not recorded';const d=new Date(v);return Number.isFinite(d.getTime())?d.toISOString().replace('T',' ').slice(0,16)+' GMT':reportEscape(v)};
export function orderedReportRows(order){
 const rows=order.resultRows?.length?order.resultRows:[{name:order.test,value:order.result,state:'Result',unit:order.unit,reference:order.reference}];
 const fields=order.template?.fields||[];const rank=r=>{const i=fields.findIndex(f=>f.name===r.name);return i<0?fields.length:i};
 return rows.map((row,i)=>({row,i})).sort((a,b)=>rank(a.row)-rank(b.row)||a.i-b.i).map(x=>x.row);
}
export const LAB_REPORT_CSS=`
.lab-report{width:210mm;min-height:297mm;max-width:none;margin:0 auto;background:#fff;border:1px solid #dce1e7;border-radius:0;padding:14mm 13mm 16mm;color:#182330;font:14px/1.45 Arial,sans-serif;box-sizing:border-box}
.lab-report *{box-sizing:border-box}.lab-report .rp-header{display:flex;align-items:center;justify-content:center;text-align:center;gap:24px;border-bottom:3px solid #aa1935;padding-bottom:20px;margin-bottom:20px;break-inside:avoid}
.lab-report .rp-brand{display:flex;flex-direction:column;align-items:center;gap:8px;width:100%}.lab-report .rp-logo{width:94px;height:64px;object-fit:contain}.lab-report .rp-center{font-size:20px;font-weight:700;letter-spacing:.3px}.lab-report .rp-address{font-size:12px;line-height:1.5;margin-top:4px}.lab-report .rp-contact{font-size:13px;font-weight:600;margin-top:5px}.lab-report .rp-subtitle{font-size:10px;letter-spacing:1.5px;margin-top:5px;color:#596675}.lab-report .rp-status{text-align:right;font-size:11px;color:#596675}.lab-report .rp-status b{display:block;color:#aa1935;font-size:13px;margin-bottom:4px}
.lab-report .rp-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px 22px;background:#f6f8fa;border:1px solid #e3e7eb;border-radius:6px;padding:17px;margin-bottom:18px;break-inside:avoid}.lab-report .rp-wide{grid-column:span 2}.lab-report .rp-item small{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.7px;color:#596675;margin-bottom:4px}.lab-report .rp-item div{font-size:13px;overflow-wrap:anywhere}.lab-report .rp-patient{font-size:16px!important;font-weight:700}.lab-report .rp-specimen{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;padding:0 2px 18px;border-bottom:1px solid #dce1e7;break-inside:avoid}
.lab-report .rp-section{margin-top:22px}.lab-report .rp-section h2{font-size:16px;margin:0 0 4px;letter-spacing:0}.lab-report .rp-caption{margin:0 0 12px;font-size:11px;color:#596675}.lab-report .rp-table{width:100%;border-collapse:collapse;table-layout:fixed;white-space:normal;font-size:12px;min-width:0}.lab-report .rp-table th{background:#eef1f4;color:#344455;font-size:10px;letter-spacing:.4px;text-transform:uppercase;text-align:left;padding:11px 8px;border-top:1px solid #cdd5dd;border-bottom:1px solid #cdd5dd}.lab-report .rp-table td{padding:11px 8px;border-bottom:1px solid #e3e7eb;vertical-align:top;overflow-wrap:anywhere;white-space:pre-wrap}.lab-report .rp-table tbody tr:nth-child(even){background:#fafbfc}.lab-report .rp-result{font-weight:700;font-size:13px}.lab-report .rp-flag{font-weight:700}.lab-report .rp-notes{border-left:3px solid #d5dce3;padding:0 0 0 13px;margin:18px 0}.lab-report .rp-notes h3{font-size:12px;margin:0 0 6px}.lab-report .rp-notes p{font-size:12px;white-space:pre-wrap;margin:0;overflow-wrap:anywhere}
.lab-report .rp-review{border-top:1px solid #bfc9d2;margin-top:26px;padding-top:15px;display:grid;grid-template-columns:1fr 1fr;gap:20px;break-inside:avoid}.lab-report .rp-signature{width:200px;max-width:100%;height:65px;object-fit:contain;object-position:left}.lab-report .rp-signature-line{width:200px;max-width:100%;height:45px;border-bottom:1px solid #6b7785;margin-top:8px}.lab-report .rp-review p{font-size:11px;margin:4px 0;overflow-wrap:anywhere}.lab-report .rp-footer{border-top:1px solid #e3e7eb;padding-top:10px;margin-top:18px;display:flex;justify-content:space-between;gap:12px;font-size:10px;color:#596675}.lab-report .reportwarning{font-size:10px;color:#596675;margin:16px 0 0}
@media screen{#app:has(.lab-report){overflow-x:auto;padding-bottom:12px}.lab-report{box-shadow:0 4px 20px #18233012}}
@media print{@page{size:A4 portrait;margin:14mm 13mm 16mm}.lab-report{width:auto;min-height:266mm;margin:0;border:0;border-radius:0;padding:0!important;max-width:none;box-shadow:none;font-size:10pt}.lab-report .rp-summary{grid-template-columns:repeat(4,minmax(0,1fr));padding:12px;gap:12px;background:#f6f8fa!important}.lab-report .rp-header{padding-bottom:14px;margin-bottom:15px}.lab-report .rp-brand{display:flex}.lab-report .rp-center{font-size:17pt}.lab-report .rp-specimen{grid-template-columns:repeat(3,minmax(0,1fr))}.lab-report .rp-review{grid-template-columns:1fr 1fr}.lab-report .rp-table{font-size:9pt;min-width:0}.lab-report .rp-table thead{display:table-header-group}.lab-report .rp-table tr{break-inside:avoid}.lab-report .rp-section h2,.lab-report .rp-caption{break-after:avoid}.lab-report .rp-table td,.lab-report .rp-table th{padding:8px 6px}.lab-report .rp-result{font-size:10pt}.lab-report{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
`;
export function renderLabReport(order,patient,{logo=''}={}){
 const e=reportEscape,item=(label,value,wide=false,patientName=false)=>'<div class="rp-item'+(wide?' rp-wide':'')+'"><small>'+e(label)+'</small><div'+(patientName?' class="rp-patient"':'')+'>'+reportText(value)+'</div></div>';
 const rows=orderedReportRows(order);
 const resultTable='<table class="rp-table"><colgroup><col style="width:29%"><col style="width:20%"><col style="width:12%"><col style="width:29%"><col style="width:10%"></colgroup><thead><tr>'+['Parameter','Result','Units','Reference interval','Flag'].map(x=>'<th scope="col">'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr><td>'+e(r.name)+'</td><td class="rp-result">'+e(r.state&&r.state!=='Result'?r.state:r.value||'Not recorded')+'</td><td>'+e(r.state&&r.state!=='Result'?'—':r.unit||'—')+'</td><td>'+e(r.reference||'Not configured')+'</td><td class="rp-flag">'+e(r.flag||'—')+'</td></tr>').join('')+'</tbody></table>';
 const ast=order.astRows?.length?'<section class="rp-section"><h2>Antimicrobial susceptibility</h2><p class="rp-caption">Standard: '+reportText(order.astStandard)+' · Version: '+reportText(order.astVersion)+'</p><table class="rp-table"><thead><tr>'+['Isolate','Antimicrobial','MIC (mg/L)','Zone (mm)','Category'].map(x=>'<th scope="col">'+x+'</th>').join('')+'</tr></thead><tbody>'+order.astRows.map(r=>'<tr>'+[r.isolate,r.agent,r.mic||'—',r.zone||'—',r.interpretation||'Not interpreted'].map(x=>'<td>'+e(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table><p class="rp-caption">'+(order.astStandard==='EUCAST'?'S: susceptible, standard dosing regimen. I: susceptible, increased exposure. R: resistant.':'Interpretation categories follow the recorded standard.')+'</p></section>':'';
 const note=(title,text)=>text?'<section class="rp-notes"><h3>'+title+'</h3><p>'+e(text)+'</p></section>':'';
 const signature=order.signature&&/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(order.signature)?'<img class="rp-signature" alt="Reviewer signature" src="'+e(order.signature)+'">':'<div class="rp-signature-line" aria-label="Reviewer signature line"></div><p>Reviewer signature</p>';
 return '<article class="report lab-report"><div class="rp-header"><div class="rp-brand">'+(logo?'<img class="rp-logo" src="'+e(logo)+'" alt="CLabs logo">':'')+'<div><div class="rp-center">CLabs</div><div class="rp-address">PR/EF/028 · TEMA COMM. 25–DAWHENYA</div><div class="rp-address">New Dawhenya, opposite Methodist Junction, Tema</div><div class="rp-contact">TEL: 0303944695 / 0576121218</div><div class="rp-subtitle">LABORATORY RESULT REPORT</div></div></div></div><section class="rp-summary" aria-label="Patient and request details">'+item('Patient name',patient?.name,true,true)+item('Patient ID',patient?.sequenceNumber??patient?.id??order.patient)+item('Accession',order.sequenceNumber??order.id)+item('Age',patientAge(patient?.dob,order.collected||order.created||order.resultAt||new Date().toISOString()))+item('Sex',patient?.sex)+item('Request ID',order.requestId||order.id)+item('Requesting clinician',order.clinician)+'</section><section class="rp-specimen" aria-label="Specimen and timing">'+item('Specimen',order.specimen)+item('Collected (as entered)',order.collected?.replace('T',' '))+item('Method / instrument',order.method)+item('Order date',reportTime(order.created))+item('Reported',reportTime(order.resultAt))+'</section><section class="rp-section"><h2>'+e(order.test)+'</h2><p class="rp-caption">'+e(order.department||'Laboratory results')+(order.amendments?.length?' · Amended report':'')+'</p>'+resultTable+'</section>'+ast+note('Request notes',order.requestNote)+note('Comments / interpretation',order.comment)+'<section class="rp-review"><div><div class="rp-item"><small>Reviewed by</small><div><b>'+reportText(order.reviewer)+'</b></div></div><p>'+reportTime(order.resultAt)+'</p>'+signature+'</div><div>'+ (order.clinicalReview?.verifiedAt?'<div class="rp-item"><small>Clinical review record</small></div><p>'+reportTime(order.clinicalReview.verifiedAt)+'</p><p>SOP / QC reference: '+e(order.clinicalReview.evidence)+'</p>':'<p class="reportwarning">Reference intervals and methods require laboratory validation before clinical release.</p>')+'</div></section></article>';
}
