export const QC_SOP_SOURCE='https://www.who.int/publications/m/item/laboratory-quality-manual';
export const GHANA_QC_REFERENCES=[{title:'Ghana Health Service — laboratory biosafety (IPC guidelines, section 17)',url:'https://ghs.gov.gh/wp-content/uploads/2022/10/IPC-Policy-and-Guidelines-FINAL-15517-1.pdf',scope:'Laboratory biosafety; not assay-specific control limits'},{title:'Ghana Ministry of Health — manuals and guidelines',url:'https://moh.gov.gh/manuals-guidelines/',scope:'Official Ghana guidance directory'},{title:'Kintampo Health Research Centre — Ghana adult reference interval study (2012)',url:'https://pubmed.ncbi.nlm.nih.gov/22558429/',scope:'Healthy adults aged 18–59; research intervals requiring local validation, not QC limits'},{title:'Ghana adult chemistry reference interval study (2022)',url:'https://pubmed.ncbi.nlm.nih.gov/35786502/',scope:'Method-specific Ghana adult research; not a universal national range'},{title:'GHS malaria case-management guidelines',url:'https://ghs.gov.gh/wp-content/uploads/2022/10/guidelines-for-case-management-of-malaria-before-press-1.pdf',scope:'Malaria diagnosis; refers to the GHS laboratory malaria SOP'}];
export function generatedSop(test){
 const name=test.name||test.test||'Test',fields=(test.fields||test.template?.fields||[]).map(f=>f.name),department=test.department||test.template?.department||'';
 let procedure='Prepare and analyse the specimen using the current manufacturer instructions and the validated laboratory method. Record reagent lots, instrument and operator. Record each requested parameter and its unit; mark tests not performed explicitly.';
 let controls='Use method-appropriate control materials and the lot-specific assigned targets / limits. Review controls, trends and corrective actions before releasing patient results.';
 let levels='Level 1, Level 2';
 const text=(name+' '+(test.format||test.template?.format||'')).toLowerCase();
 if(/rapid|rdt/.test(text)){procedure='Check specimen suitability, kit storage, expiry and lot. Prepare the specimen, add sample / buffer and read at the times specified by this kit’s instructions. Record the control-line validity and all test bands. Invalid devices must be repeated using a new device.';controls='Record external positive and negative controls at the frequency specified by the kit and local SOP, including new lots / shipments where required. Verify the internal control for each patient device; an internal control is not a substitute for required external controls.';levels='Positive, Negative';}
 else if(/screen|qualitative|antibody|antigen|allerg/.test(text)){procedure='Prepare and test the specimen using the assay-specific manufacturer procedure and locally validated method. Verify calibration or assay validity, record the measured signal / reported category and apply the approved assay cutoffs. Follow the test-specific confirmation or referral pathway where required.';controls='Use appropriate reactive / positive and non-reactive / negative controls according to the assay instructions, including calibration and lot-change checks where required. Record measured observations and acceptance against assay-specific targets.';levels='Positive, Negative';} else if(/culture|ast/.test(text)){procedure='Use the locally approved specimen-specific inoculation, media and incubation procedure. Examine growth, document identification tests and perform susceptibility testing only for appropriate isolates using the adopted current breakpoint standard.';controls='Document medium sterility / growth performance, identification-control organisms and susceptibility QC strains appropriate to the method. Use current adopted QC ranges; record corrective action for failed controls.';levels='Method control';}
 else if(/compatibility|crossmatch|blood group|coombs/.test(text)){procedure='Confirm patient and specimen identity against the transfusion request. Perform the specified grouping / compatibility or antiglobulin method using validated reagents and the approved transfusion laboratory SOP. Resolve discrepancies and document reactions before authorised interpretation.';controls='Use reagent-specific positive and negative cells / controls and antiglobulin check cells when required by the method. Document reagent performance and identity checks; resolve discrepancies before release.';levels='Positive, Negative';}
 else if(/microscopy|film|urine|stool|semen|fluid/.test(text)){procedure='Check collection, transport and sample suitability. Prepare slides / chambers with the validated method. Examine systematically and record the requested findings, counts, units and any applicable counting calculation. Obtain a second review where the local method requires it.';controls='Verify stains / reagents with appropriate positive and negative material, microscope performance, counting equipment and staff competency. Record method-specific QC and agreement checks.';levels='Method control';}
 else if(department==='Electrocardiogram'){procedure='Confirm identity, indication and recording conditions. Position the patient, prepare skin and place electrodes using the approved ECG recording method. Verify lead placement and recording settings; acquire an artefact-free trace and document measurements and interpretation by a qualified reviewer.';controls='Record equipment safety / maintenance checks and verify calibration, speed, gain, lead integrity and artefact handling against the equipment manual and local procedure.';levels='Equipment check';}
 else if(department==='Ultrasound'){procedure='Confirm identity, indication and required patient preparation. Select the appropriate probe and validated examination protocol. Acquire and retain required views and measurements, describe findings and document impression and limitations with qualified review.';controls='Record probe / equipment checks, image quality and measurement performance against the equipment manual and local quality-assurance schedule.';levels='Equipment check';}
 return {code:'KDC-SOP-'+test.id,version:'1',title:name,specimen:test.specimen||test.template?.specimen||'',parameters:fields,procedure,controls,levels,criteria:'Enter the manufacturer / control-lot acceptance limits and the locally approved acceptance rules.',frequency:'Enter the method-specific QC frequency from the manufacturer instructions and laboratory policy.',method:'',reference:'',validHours:24,status:'Draft',source:QC_SOP_SOURCE,ghanaReferences:GHANA_QC_REFERENCES.filter((r,i)=>i<2||(i<4&&['Chemistry','Hematology','Endocrinology'].includes(department))||/malaria/i.test(name)),referenceIntervals:'Use the locally validated, method-specific patient reference intervals saved in the test template. Ghana adult chemistry research intervals are provisional; they are not QC limits.'};
}
export function eligibleQc(sop,testId,method,records,at=Date.now()){
 if(sop?.status!=='Approved'||!method||method.trim().toLowerCase()!==sop.method.trim().toLowerCase())return [];
 const relevant=records.filter(q=>q.testId===testId&&q.sopVersion===sop.version&&q.sopCode===sop.code&&q.analyzer?.trim().toLowerCase()===method.trim().toLowerCase()&&q.runId&&q.performedAt&&new Date(q.performedAt).getTime()<=at&&at-new Date(q.performedAt).getTime()<=Number(sop.validHours)*3600000).sort((a,b)=>new Date(b.performedAt)-new Date(a.performedAt)||new Date(b.created)-new Date(a.created));
 if(!relevant.length)return [];
 const run=relevant[0].runId,latest=new Map();for(const q of relevant.filter(q=>q.runId===run))if(!latest.has(q.level))latest.set(q.level,q);
 const required=sop.levels.split(',').map(x=>x.trim()).filter(Boolean);
 const rows=required.map(level=>latest.get(level));return rows.length&&rows.every(q=>q?.acceptance==='Accepted'&&q.acceptedBy&&q.criteria&&String(q.value).trim())?rows:[];
}
