import {patientAge} from './patient-age.js';
const usEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderUltrasoundReport(report,patient,{logo=''}={}){
 const e=usEscape,item=(label,value)=>'<div class="rp-item"><small>'+e(label)+'</small><div>'+e(value||'Not recorded')+'</div></div>';
 const section=(title,value)=>value?'<section class="rp-notes"><h3>'+e(title)+'</h3><p>'+e(value)+'</p></section>':'';
 const time=v=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toISOString().replace('T',' ').slice(0,16)+' GMT':'Not recorded';
 const signature=report.signature&&/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(report.signature)?'<img class="rp-signature" src="'+e(report.signature)+'" alt="Approver signature">':'<div class="rp-signature-line"></div>';
 return '<article class="report lab-report"><div class="rp-header"><div class="rp-brand">'+(logo?'<img class="rp-logo" src="'+e(logo)+'" alt="CLabs logo">':'')+'<div><div class="rp-center">CLabs</div><div class="rp-address">PR/EF/028 · TEMA COMM. 25–DAWHENYA</div><div class="rp-address">New Dawhenya, opposite Methodist Junction, Tema</div><div class="rp-contact">TEL: 0303944695 / 0576121218</div><div class="rp-subtitle">ULTRASOUND REPORT</div></div></div></div><section class="rp-summary">'+item('Patient name',patient?.name)+item('Patient ID',patient?.sequenceNumber??patient?.id)+item('Age',patientAge(patient?.dob,report.examAt||report.created))+item('Sex',patient?.sex)+item('Scan number',report.sequenceNumber??report.id)+item('Examination',report.test)+item('Examined',time(report.examAt))+item('Referring clinician',report.clinician)+'</section><section class="rp-specimen">'+item('Sonographer',report.operator)+item('Equipment',report.equipment)+item('Technique / approach',report.technique)+'</section>'+section('Clinical indication',report.indication)+'<section class="rp-section"><h2>Findings</h2>'+(report.resultRows||[]).map(row=>section(row.name,row.state==='Result'?row.value+(row.unit?' '+row.unit:''):row.state)).join('')+'</section>'+section('Impression',report.impression)+section('Recommendations / follow-up',report.recommendation)+'<section class="rp-review"><div>'+item('Approved by',report.reviewer)+signature+'<small>Approver signature</small></div><div>'+item('Report status',report.amendments?.length?'Final · Amended':'Final')+item('Approved',time(report.resultAt))+(report.amendments?.length?section('Latest amendment reason',report.amendments.at(-1).reason):'')+'</div></section></article>';
}
