import { build } from 'esbuild';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
const assets={};
function publicImage(file,type){const bytes=fs.readFileSync(file),hash=createHash('sha256').update(bytes).digest('hex').slice(0,16),url='/assets/'+hash+'-'+file.split('/').at(-1);assets[url]={type,body:bytes.toString('base64')};return url}
const heroUrl=publicImage('web/assets/knox-lab-hero.jpg','image/jpeg');
const logoUrl=publicImage('web/assets/clabs-logo.svg','image/svg+xml');
const hero=fs.readFileSync('web/assets/knox-lab-hero.jpg').toString('base64');
const logo=fs.readFileSync('web/assets/clabs-logo.svg').toString('base64');
const recordsCode=fs.readFileSync('web/record-delta.js','utf8').replace(/^export /gm,'')+'\n'+fs.readFileSync('web/records.js','utf8');
const permissionsCode=fs.readFileSync('worker/permissions.js','utf8').replace(/^export /gm,'')+'\n'+fs.readFileSync('web/permissions.js','utf8')+'\n'+fs.readFileSync('web/result-email.js','utf8');
const offlineCode=fs.readFileSync('web/offline-merge.js','utf8').replace(/^export /gm,'')+'\n'+fs.readFileSync('web/offline.js','utf8');
const transportCode=fs.readFileSync('web/transport.js','utf8').replace(/^export /gm,'');
const html=fs.readFileSync('web/index.html','utf8').replace('/*__FEATURE_UPDATES__*/',fs.readFileSync('web/ecg.js','utf8')+'\n'+fs.readFileSync('web/change-audit.js','utf8')+'\n'+fs.readFileSync('web/result-approval.js','utf8')+'\n'+fs.readFileSync('shared/qc-sop.js','utf8').replace(/^export /gm,'')+'\n'+fs.readFileSync('web/qc-sop.js','utf8')).replace('/*__REPORT__*/',fs.readFileSync('shared/lab-report.js','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'')+'\n'+fs.readFileSync('web/report-view.js','utf8')).replace('/*__ULTRASOUND__*/',fs.readFileSync('shared/ultrasound-report.js','utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'')+'\n'+fs.readFileSync('web/ultrasound.js','utf8')).replace('/*__MONTHLY_REPORT__*/',fs.readFileSync('web/monthly-report.js','utf8')+'\n'+fs.readFileSync('web/ultrasound-summary.js','utf8')).replace('/*__STOCK__*/',fs.readFileSync('web/stock.js','utf8')).replace('/*__ATTENDANCE__*/',fs.readFileSync('web/attendance.js','utf8')).replace('/*__TRANSPORT__*/',fs.readFileSync('shared/patient-age.js','utf8').replace(/^export /gm,'')+'\n'+transportCode).replace('/*__CHEMISTRY__*/',fs.readFileSync('web/chemistry.js','utf8')).replace('/*__OFFLINE__*/',offlineCode).replace('/*__PERMISSIONS__*/',permissionsCode).replace('/*__RECORDS__*/',recordsCode).replaceAll('__KNOX_HERO_DATA__',heroUrl).replaceAll('__KNOX_LOGO_DATA__',logoUrl);
const serviceWorker=fs.readFileSync('web/sw.js','utf8').replace('/*__PUBLIC_ASSETS__*/',JSON.stringify(Object.keys(assets)));
const api=fs.readFileSync('worker/api.js','utf8');
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/server',{recursive:true});fs.mkdirSync('dist/.openai',{recursive:true});
await build({entryPoints:['worker/api.js'],bundle:true,format:'esm',platform:'browser',target:'es2022',outfile:'dist/server/index.js',banner:{js:'const PUBLIC_IMAGES='+JSON.stringify(assets)+'; const DEVICE_GATEWAY_SOURCE='+JSON.stringify(fs.readFileSync('integration/device-gateway.mjs','utf8'))+'; const REPORT_LOGO='+JSON.stringify('data:image/svg+xml;base64,'+logo)+'; const NUMBER_SCHEMA_SQL='+JSON.stringify(fs.readFileSync('postgres/003_record_numbers.sql','utf8'))+'; const RECORD_SCHEMA_SQL='+JSON.stringify(fs.readFileSync('postgres/002_record_storage.sql','utf8'))+'; const HTML='+JSON.stringify(html)+'; const SERVICE_WORKER='+JSON.stringify(serviceWorker)+';'},conditions:['workerd','browser'],external:['node:*']});
fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');
console.log('Built authenticated Worker and UI');
