import {stampQualityRecords,qcRecords,attachQualityEvidence} from './qc-sop.js';
import {recordChangeEvents} from './change-audit.js';
import {monthlyReport,ultrasoundSummary,stampCompletionDates} from './monthly-report.js';
import {listStock,saveStockItem,recordStockMovement,stockConsumption,ensureStock} from './stock.js';
import {DEVICE_BRANDS,deviceSettings,savedDeviceSettings,deviceReadiness} from './device-integration.js';
import {prepareUltrasoundChanges} from './ultrasound.js';
import {visibleUltrasoundState} from './ultrasound-privacy.js';
import {visibleFinancialState,protectSalesWrites} from './sales-privacy.js';
import {listAttendance,recordAttendance} from './attendance.js';
import {readRecords,prepareDelta,persistDelta,recordSummary,ensureRecords,receiptRecords} from './record-state.js';
import {recordDelta} from '../web/record-delta.js';
import {prepareResultEmail} from './result-email.js';
import {PERMISSIONS,DEFAULT_PERMISSIONS,permissionsFor,requirePermission,authorizeChanges,canViewSales,can} from './permissions.js';
import {selectDatabase,migrateDatabase} from './postgres.js';
const visibleState=(user,state,receiptOrderId=null)=>visibleUltrasoundState(user,visibleFinancialState(user,state,receiptOrderId));
const ROLES=['admin','ceo','scientist','reception','viewer'];
const initialData=()=>({patients:[],orders:[],qc:[],analyzers:[],activity:[],customTests:[],testConfig:{},prices:[],sales:[],ultrasoundReports:[]});
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const q=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function digest(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function body(req,max=2000000){const reader=req.body?.getReader();if(!reader)return{};let size=0,parts=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();fail(413,'Request too large')}parts.push(value)}let bytes=new Uint8Array(size),pos=0;for(const p of parts){bytes.set(p,pos);pos+=p.length}try{return JSON.parse(new TextDecoder().decode(bytes))}catch{fail(400,'Invalid JSON')}}
function sameOrigin(req){if(req.method==='GET'||req.method==='HEAD')return;const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)fail(403,'Cross-origin request rejected');if(req.headers.get('sec-fetch-site')==='cross-site')fail(403,'Cross-site request rejected');if(!req.headers.get('content-type')?.includes('application/json'))fail(415,'Use application/json')}
async function identity(req,env){
  const platformUid=req.headers.get('oai-authenticated-user-id');
  const platformEmail=req.headers.get('oai-authenticated-user-email');
  const manualEmail=req.headers.get('x-knox-username')?.trim();
  const manualPassword=req.headers.get('x-knox-password')||'';
  if(!manualEmail||!manualPassword)fail(401,'Enter your laboratory username and password');
  const email=manualEmail.toLowerCase();
  if(!email||(!manualEmail&&!platformUid))fail(401,'Enter your laboratory username to continue');
  const suppliedHash=manualEmail?(manualPassword?await digest(manualPassword):''):null;
  if(manualEmail&&!manualPassword)fail(401,'Enter your password to continue');
  if(email===env.KNOX_OWNER_EMAIL?.toLowerCase()){
    if(manualEmail&&(!env.KNOX_OWNER_PASSWORD_HASH||suppliedHash!==env.KNOX_OWNER_PASSWORD_HASH))fail(401,'Invalid username or password');
    return {email,name:'Admin (Administrator)',role:'admin',owner:true,auth:manualEmail?'manual-username':'chatgpt',passwordRequired:true}
  }
  const u=await q(env,'SELECT s.email,s.name,s.role,s.password_hash,s.active,a.position,a.permissions FROM staff s LEFT JOIN staff_access a ON a.email=s.email WHERE s.email=?',email).first();
  if(!u||!u.active)fail(403,'Your username has not been granted staff access. Ask the administrator.');
  if(manualEmail&&(!u.password_hash||suppliedHash!==u.password_hash))fail(401,'Invalid username or password');
  return {email:u.email,name:u.name,role:u.role,position:u.position||u.role,permissions:u.permissions?JSON.parse(u.permissions):DEFAULT_PERMISSIONS[u.role]||[],owner:false,auth:manualEmail?'manual-username':'chatgpt',passwordRequired:true}
}
function permit(user,roles){if(!roles.includes(user.role))fail(403,'Your role does not permit this action')}
export function validateRelease(o,data){
 const text=v=>typeof v==='string'&&v.trim().length>0;
 const p=data.patients.find(p=>p.id===o.patient);
 if(!p||!text(p.name)||!text(p.dob)||!text(p.sex))fail(422,'Complete patient name, date of birth and sex before review');
 if(!o.received||!text(o.specimen)||!text(o.method))fail(422,'Receive the specimen and record the method before review');
 const a=o.clinicalReview;
 if(!a||a.identity!==true||a.qc!==true||a.references!==true||!text(a.evidence))fail(422,'Document patient identity, QC and reference interval verification with an SOP / QC record reference');
 if(!o.template?.fields?.length||!Array.isArray(o.resultRows)||o.resultRows.length!==o.template.fields.length)fail(422,'A complete structured result template is required for review');
 o.resultRows.forEach((r,i)=>{
 const f=o.template.fields[i];
 if(r.name!==f.name||!['Result','Not performed','Not applicable'].includes(r.state))fail(422,'Result fields do not match the order template');
 if(r.state!=='Result')return;
 if(!text(r.value))fail(422,'Complete result: '+f.name);
 if(f.type==='number'&&!/^(?:[<>]=?|[≤≥])?\s*-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(r.value))fail(422,'Invalid numeric result: '+f.name);
 if(o.testId==='ECG12'&&f.type==='number'&&r.unit!==f.unit)fail(422,'Use the configured ECG measurement unit for '+f.name);
 if(o.testId!=='ECG12'&&f.type==='number'&&(!text(r.unit)||!text(r.reference)||/PROVISIONAL|not configured|not supplied/i.test(r.reference)))fail(422,'Supply laboratory-approved units and a patient-appropriate reference interval for '+f.name);
 if(r.flag==='Critical'&&!text(a.criticalNotification))fail(422,'Document critical-result recipient, notification time and read-back');
 });
}
async function audit(env,u,action){await q(env,'INSERT INTO audit(id,actor,action,created) VALUES(?,?,?,?)',id(),u.email,action,now()).run()}
async function state(env,options={}){if(env.DB.sql)return readRecords(env.DB,options);await q(env,'INSERT INTO workspace(id,revision,data) VALUES(1,0,?) ON CONFLICT(id) DO NOTHING',JSON.stringify(initialData())).run();const r=await q(env,'SELECT revision,data FROM workspace WHERE id=1').first();return {revision:r.revision,data:JSON.parse(r.data)}}
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function validateState(data){if(!data||typeof data!=='object'||Array.isArray(data))fail(400,'Invalid workspace');const keys=['patients','orders','qc','analyzers','activity','customTests','prices','sales','ultrasoundReports'];for(const k of keys){if(!Array.isArray(data[k])||data[k].length>10000)fail(400,'Invalid '+k);if(k!=='activity'&&data[k].some(r=>!r||typeof r!=='object'||typeof r.id!=='string'||! /^[A-Za-z0-9_-]{1,100}$/.test(r.id)))fail(400,'Invalid record identifiers');if(k!=='activity'&&new Set(data[k].map(x=>x.id)).size!==data[k].length)fail(400,'Duplicate record identifiers')}if(!data.testConfig||Array.isArray(data.testConfig)||typeof data.testConfig!=='object')fail(400,'Invalid test configuration');for(const k of Object.keys(data))if(![...keys,'testConfig'].includes(k))fail(400,'Unknown workspace field');const pids=new Set(data.patients.map(p=>p.id));for(const o of data.orders)if(!pids.has(o.patient))fail(400,'An order references an unknown patient');for(const report of data.ultrasoundReports)if(!pids.has(report.patient))fail(400,'An ultrasound report references an unknown patient');for(const sale of data.sales)if(sale.patient&&!pids.has(sale.patient))fail(400,'A sale references an unknown patient')}
async function storeState(env,user,payload,internalCurrent=null){if(!payload||typeof payload!=='object'||(!env.DB.sql&&(!payload.data||typeof payload.data!=='object')))fail(400,'Invalid workspace');let legacyCurrent=null;if(!env.DB.sql&&(!canViewSales(user)||!can(user,'ultrasoundView'))){legacyCurrent=await state(env);if(!can(user,'ultrasoundView')){if((payload.data.ultrasoundReports||[]).length)requirePermission(user,'ultrasoundView');payload.data.ultrasoundReports=legacyCurrent.data.ultrasoundReports;}if(!canViewSales(user)){protectSalesWrites(user,legacyCurrent.data.sales,payload.data?.sales||[]);payload.data.sales=[...legacyCurrent.data.sales,...(payload.data.sales||[]).filter(s=>!legacyCurrent.data.sales.some(old=>old.id===s.id))];}}if(env.DB.sql&&internalCurrent)payload={revision:payload.revision,...recordDelta(internalCurrent.data,payload.data)};const prepared=env.DB.sql?await prepareDelta(env.DB,payload):null;if(prepared){if(!canViewSales(user)&&(payload.changes?.sales?.remove||[]).length)fail(403,'Only CEO and administrator accounts may delete sales records');protectSalesWrites(user,prepared.current.data.sales,prepared.data.sales);payload={...payload,data:prepared.data};}validateState(payload.data);const invoiced=new Set();for(const sale of payload.data.sales){if(sale.orderId&&sale.status!=='Cancelled'){if(invoiced.has(sale.orderId))fail(422,'An order cannot have duplicate active sales');invoiced.add(sale.orderId);const order=payload.data.orders.find(o=>o.id===sale.orderId);if(!order||order.patient!==sale.patient)fail(422,'Receipt patient must match the order');if(!Number.isFinite(sale.total)||sale.total<0||sale.total!==sale.quantity*sale.unitPrice)fail(422,'Invalid receipt amount')}}const current=prepared?.current||legacyCurrent||await state(env);if(payload.revision!==current.revision)fail(409,'Another staff member changed the workspace. Reload shared records before saving again. Your unsaved changes remain visible.');authorizeChanges(user,current.data,payload.data);recordChangeEvents(current.data,payload.data,user,payload.changeReasons);stampQualityRecords(current.data,payload.data,user);prepareUltrasoundChanges(user,current.data,payload.data);for(const report of payload.data.ultrasoundReports){const old=current.data.ultrasoundReports.find(r=>r.id===report.id);if(report.reviewed&&!equal(old,report))await attachQualityEvidence(env,report,payload.data);}for(const o of payload.data.orders){const prev=current.data.orders.find(x=>x.id===o.id);const orderChanged=!equal(o,prev);if(orderChanged)o.patientId=o.patient;if(o.signature&&(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(o.signature)||o.signature.length>200000))fail(422,'Invalid signature image');if(o.reviewed&&(!prev?.reviewed||orderChanged)){await attachQualityEvidence(env,o,payload.data);validateRelease(o,payload.data);o.reviewer=user.name;o.reviewerEmail=user.email;o.resultAt=now();o.clinicalReview.verifiedBy=user.email;o.clinicalReview.verifiedAt=o.resultAt}}
stampCompletionDates(current.data,payload.data,now());
const changeEvents=recordChangeEvents(current.data,payload.data,user,payload.changeReasons);payload={...payload,changeEvents};
if(env.DB.sql)return persistDelta(env.DB,user,payload,current,payload.data);
await ensureStock(env);const stockCommands=await stockConsumption(env,user,current.data,payload.data);let result;
try{await env.DB.batch([q(env,'UPDATE workspace SET data=?,revision=revision+1 WHERE id=1 AND revision=?',JSON.stringify(payload.data),payload.revision),q(env,'UPDATE stock_write_guard SET revision=CASE WHEN changes()=1 THEN ? ELSE NULL END WHERE id=1',payload.revision+1),...stockCommands,...changeEvents.map(event=>q(env,'INSERT INTO audit(id,actor,action,created) VALUES(?,?,?,?)',id(),user.email,JSON.stringify(event),event.at)),q(env,'INSERT INTO audit(id,actor,action,created) VALUES(?,?,?,?)',id(),user.email,'Saved laboratory records (revision '+(payload.revision+1)+')',now())]);result={revision:payload.revision+1};}catch(e){if(/constraint/i.test(e.message))fail(409,'Workspace changed. Reload before saving.');throw e}return {revision:result.revision,data:payload.data}}
export function parseHL7(raw){if(typeof raw!=='string'||raw.length>200000)fail(400,'Invalid HL7 payload');raw=raw.replace(/^\x0b/,'').replace(/\x1c\r?$/,'');const segments=raw.split(/\r\n|\r|\n/).filter(Boolean).map(s=>s.split('|'));const msh=segments[0];if(msh?.[0]!=='MSH'||msh[1]!=='^~\\&'||!msh[8]?.startsWith('ORU^R01'))fail(422,'Only HL7 ORU^R01 with standard separators is supported by this adapter');const obr=segments.filter(s=>s[0]==='OBR');if(obr.length!==1)fail(422,'Send exactly one OBR sample per message');const messageId=msh[9],sampleId=(obr[0][3]||obr[0][2]||'').split('^')[0];const results=segments.filter(s=>s[0]==='OBX').map(s=>{if(!['NM','ST','SN'].includes(s[2]))fail(422,'Unsupported OBX value type');if(!['F','C'].includes(s[11]))fail(422,'Only final or corrected observations are accepted into the review inbox');if(/[~\\]/.test(s[5]||''))fail(422,'Repeated or escaped OBX values require a model-specific adapter');if(s[2]==='SN')fail(422,'Structured numeric values require model-specific normalization');return {code:(s[3]||'').split('^')[0],value:s[5],unit:(s[6]||'').split('^')[0],reference:s[7]||'',flag:s[8]||''}});return {messageId,sampleId,results}}
function validateMessage(p){if(typeof p.messageId!=='string'||!p.messageId||p.messageId.length>160||typeof p.sampleId!=='string'||!p.sampleId||p.sampleId.length>160||!Array.isArray(p.results)||!p.results.length||p.results.length>300)fail(400,'messageId, sampleId and 1–300 results are required');for(const r of p.results){if(typeof r.code!=='string'||!r.code||typeof r.value!=='string'||!r.value||r.value.length>1000||typeof r.unit!=='string')fail(400,'Each result needs code, string value and unit');}if(new Set(p.results.map(r=>r.code)).size!==p.results.length)fail(422,'Duplicate observation codes need model-specific normalization')}
async function deviceIdentity(req,env,interfaceId){const it=await q(env,'SELECT * FROM interfaces WHERE id=? AND active=1',interfaceId).first();if(!it)fail(401,'Invalid interface credentials');const token=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(!token||await digest(token)!==it.token_hash)fail(401,'Invalid interface credentials');return it}
async function deviceProtocol(env,it,format){const protocol=format==='hl7'?'HL7':format==='json'||format===undefined?'JSON':null;if(!protocol)fail(422,'Use normalized JSON or HL7 ORU^R01');if(it.protocol==='AUTO'){await q(env,"UPDATE interfaces SET protocol=? WHERE id=? AND protocol='AUTO'",protocol,it.id).run();it.protocol=(await q(env,'SELECT protocol FROM interfaces WHERE id=?',it.id).first()).protocol;}if(it.protocol!==protocol)fail(422,'Payload does not match the configured adapter');return protocol}
function deviceConfiguration(it,payload=null){const settings=deviceSettings(it.mapping);return {id:it.id,name:it.name,model:it.model,device:settings.device,protocol:it.protocol,mapping:settings.mapping,endpoint:'/api/devices/'+it.id+'/messages',configurationEndpoint:'/api/devices/'+it.id+'/configuration',...deviceReadiness(it,payload),releaseMode:'draft_review_required'}}
async function deviceConnect(req,env,interfaceId){const it=await deviceIdentity(req,env,interfaceId);if(req.method==='POST'){const b=await body(req,10000);if(b.model&&b.model!==it.model)fail(422,'Gateway model does not match the registered device');if(!['json','hl7'].includes(b.format))fail(422,'Gateway must declare json or hl7');await deviceProtocol(env,it,b.format);it.last_seen=now();await q(env,'UPDATE interfaces SET last_seen=? WHERE id=?',it.last_seen,it.id).run();}const last=await q(env,'SELECT payload FROM messages WHERE interface_id=? ORDER BY created DESC LIMIT 1',it.id).first();return json(deviceConfiguration(it,last?JSON.parse(last.payload):null))}
async function ingest(req,env,interfaceId){const it=await deviceIdentity(req,env,interfaceId);const b=await body(req,250000);const p=b.format==='hl7'?parseHL7(b.raw):b;validateMessage(p);await deviceProtocol(env,it,b.format);const existing=await q(env,'SELECT id,payload FROM messages WHERE interface_id=? AND message_id=?',it.id,p.messageId).first();if(existing){if(!equal(JSON.parse(existing.payload),p))fail(409,'Message ID was reused with different content');it.last_seen=now();await q(env,'UPDATE interfaces SET last_seen=? WHERE id=?',it.last_seen,it.id).run();return json({accepted:true,duplicate:true,id:existing.id,configuration:deviceConfiguration(it,p)})}const mid=id();it.last_seen=now();await env.DB.batch([q(env,'INSERT INTO messages(id,interface_id,message_id,sample_id,payload,status,created) VALUES(?,?,?,?,?,?,?)',mid,it.id,p.messageId,p.sampleId,JSON.stringify(p),'pending',it.last_seen),q(env,'UPDATE interfaces SET last_seen=? WHERE id=?',it.last_seen,it.id)]);return json({accepted:true,id:mid,status:'pending_review',configuration:deviceConfiguration(it,p)},202)}
const staffAccessReady=new WeakMap();
async function ensureStaffAccess(env){if(!staffAccessReady.has(env.DB)){const ready=q(env,'CREATE TABLE IF NOT EXISTS staff_access (email TEXT PRIMARY KEY, position TEXT NOT NULL, permissions TEXT NOT NULL)').run().catch(error=>{staffAccessReady.delete(env.DB);throw error});staffAccessReady.set(env.DB,ready)}await staffAccessReady.get(env.DB);}
async function routes(req,env){const path=new URL(req.url).pathname;const incoming=path.match(/^\/api\/(?:devices|mindray)\/([^/]+)\/messages$/);if(incoming&&req.method==='POST')return ingest(req,env,incoming[1]);const connect=path.match(/^\/api\/devices\/([^/]+)\/(configuration|connect)$/);if(connect&&((connect[2]==='configuration'&&req.method==='GET')||(connect[2]==='connect'&&req.method==='POST')))return deviceConnect(req,env,connect[1]);sameOrigin(req);await ensureStaffAccess(env);const user=await identity(req,env);
if(path==='/api/results/email-draft'&&req.method==='POST'){requirePermission(user,'emailResults');const b=await body(req,10000);const s=await state(env,{collection:'orders',orderId:b.orderId});if(b.revision!==s.revision)fail(409,'Records have changed. Reload before preparing an email.');const order=s.data.orders.find(o=>o.id===b.orderId);if(!order)fail(404,'Result not found');const draft=prepareResultEmail(order,s.data.patients.find(p=>p.id===order.patient),String(b.recipient||'').trim());await audit(env,user,'Result email draft prepared (not sent): '+order.id+' to '+draft.recipient);return json(draft);}
if(path==='/api/attendance'&&req.method==='GET')return json(await listAttendance(env,user,new URL(req.url).searchParams.get('date')||now().slice(0,10)));
if(path==='/api/attendance'&&req.method==='POST')return json(await recordAttendance(env,user,await body(req,10000)));
if(path==='/api/stocks'&&req.method==='GET')return json(await listStock(env,user,new URL(req.url).searchParams.get('itemId')||''));
if(path==='/api/stocks/items'&&req.method==='POST')return json(await saveStockItem(env,user,await body(req,30000)));
if(path==='/api/stocks/movements'&&req.method==='POST')return json(await recordStockMovement(env,user,await body(req,10000)));
if(path==='/api/ultrasound/summary'&&req.method==='GET')return json(await ultrasoundSummary(env,user,new URL(req.url).searchParams.get('month'),()=>state(env)));
if(path==='/api/reports/monthly'&&req.method==='GET')return json(await monthlyReport(env,user,Object.fromEntries(new URL(req.url).searchParams),()=>state(env)));
if(path==='/api/qc/context'&&req.method==='GET'){if(!can(user,'qc')&&!can(user,'review')&&!can(user,'ultrasoundReview'))requirePermission(user,'qc');const testId=new URL(req.url).searchParams.get('testId');if(!testId||testId.length>100)fail(400,'Select a test');if(env.DB.sql)await ensureRecords(env.DB);const current=await state(env);return json({sop:current.data.testConfig[testId]?.qcSop||null,records:await qcRecords(env,testId,current.data)});}
if(path==='/api/me')return json({user});
if(path==='/api/state'&&req.method==='GET'){const options=Object.fromEntries(new URL(req.url).searchParams);if(options.collection==='ultrasoundReports')requirePermission(user,'ultrasoundView');if(options.collection==='sales'&&!canViewSales(user))fail(403,'Sales history is restricted to CEO and administrator accounts');return json(visibleState(user,await state(env,options)));}
if(path==='/api/state/read'&&req.method==='POST'){const options=await body(req,250000);if(options.collection==='ultrasoundReports')requirePermission(user,'ultrasoundView');if(options.collection==='sales'&&!canViewSales(user))fail(403,'Sales history is restricted to CEO and administrator accounts');return json(visibleState(user,await state(env,options)));}
if(path==='/api/receipt-context'&&req.method==='POST'){if(!canViewSales(user))requirePermission(user,'finance');const b=await body(req,10000);if(!env.DB.sql)return json(visibleState(user,await state(env),b.orderId));await ensureRecords(env.DB);return json(visibleState(user,await receiptRecords(env.DB,b.orderId),b.orderId));}
if(path==='/api/summary'&&req.method==='GET'){if(!env.DB.sql)return json(canViewSales(user)?{counts:{},finance:{}}:{counts:{}});await ensureRecords(env.DB);const summary=await recordSummary(env.DB,canViewSales(user)&&new URL(req.url).searchParams.get('countsOnly')!=='1');if(!can(user,'ultrasoundView'))delete summary.counts.ultrasoundReports;return json(summary);}
if(path==='/api/state'&&req.method==='PUT')return json(visibleState(user,await storeState(env,user,await body(req))));
if(path==='/api/staff'&&req.method==='GET'){permit(user,['admin']);const r=await q(env,'SELECT email,name,role,active,created FROM staff ORDER BY name').all();const access=(await q(env,'SELECT email,position,permissions FROM staff_access').all()).results;return json({staff:[{email:env.KNOX_OWNER_EMAIL,name:'Admin (Administrator)',role:'admin',active:1,owner:true},...r.results.filter(u=>u.email!==env.KNOX_OWNER_EMAIL).map(u=>{const a=access.find(a=>a.email===u.email);return {...u,position:a?.position||u.role,permissions:a?JSON.parse(a.permissions):DEFAULT_PERMISSIONS[u.role]||[]}})]})}
if(path==='/api/staff'&&req.method==='POST'){permit(user,['admin']);const b=await body(req,10000),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||'');if(!/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(email)||!name||name.length>100||!ROLES.includes(b.role))fail(400,'Enter a valid email, name and role');if(email===env.KNOX_OWNER_EMAIL)fail(400,'The owner administrator cannot be changed here');if(password&&password.length<8)fail(400,'Passwords must be at least 8 characters');const position=String(b.position||b.role).trim().slice(0,100);const permissions=b.permissions===undefined?DEFAULT_PERMISSIONS[b.role]:b.permissions;if(!Array.isArray(permissions)||permissions.some(p=>!Object.hasOwn(PERMISSIONS,p)))fail(400,'Invalid staff permissions');const existing=await q(env,'SELECT password_hash FROM staff WHERE email=?',email).first();if(!existing&&!password)fail(400,'A password is required for new staff');const passwordHash=password?await digest(password):existing?.password_hash||null;if(existing)await q(env,'UPDATE staff SET name=?,role=?,password_hash=?,active=? WHERE email=?',name,b.role,passwordHash,b.active===false?0:1,email).run();else await q(env,'INSERT INTO staff(email,name,role,password_hash,active,created) VALUES(?,?,?,?,?,?)',email,name,b.role,passwordHash,b.active===false?0:1,now()).run();await q(env,'INSERT INTO staff_access(email,position,permissions) VALUES(?,?,?) ON CONFLICT(email) DO UPDATE SET position=excluded.position,permissions=excluded.permissions',email,position,JSON.stringify([...new Set(permissions)])).run();await audit(env,user,'Staff access updated: '+email+' / '+b.role);return json({ok:true})}
if(path==='/api/audit'&&req.method==='GET'){permit(user,['admin']);const after=new URL(req.url).searchParams.get('after')||'';if(after.length>100)fail(400,'Invalid audit cursor');const events=(await (after?q(env,'SELECT id,actor,action,created FROM audit WHERE (created,id)<(SELECT created,id FROM audit WHERE id=?) ORDER BY created DESC,id DESC LIMIT 51',after):q(env,'SELECT id,actor,action,created FROM audit ORDER BY created DESC,id DESC LIMIT 51')).all()).results;return json({events:events.slice(0,50),next:events.length>50?events[49].id:null})}
if(path==='/api/interfaces'&&req.method==='GET'){if(!permissionsFor(user).includes('analyzers'))requirePermission(user,'importResults');const interfaces=(await q(env,'SELECT i.id,i.name,i.model,i.protocol,i.active,i.mapping,i.last_seen,i.created,(SELECT payload FROM messages WHERE interface_id=i.id ORDER BY created DESC LIMIT 1) AS last_payload FROM interfaces i ORDER BY i.created DESC').all()).results;return json({brands:DEVICE_BRANDS,interfaces:interfaces.map(it=>({...deviceConfiguration(it,it.last_payload?JSON.parse(it.last_payload):null),active:it.active,last_seen:it.last_seen,created:it.created}))})}
if(path==='/api/interfaces'&&req.method==='POST'){requirePermission(user,'analyzers');const b=await body(req,100000);if(!b.name||!b.model||!['AUTO','JSON','HL7'].includes(b.protocol))fail(400,'Specify a name, model and supported adapter');const mapping=savedDeviceSettings(b.mapping||{},b.device||{});const token='knox_'+crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),iid=b.id||id(),hash=await digest(token);if(b.id){const exists=await q(env,'SELECT id FROM interfaces WHERE id=?',iid).first();if(!exists)fail(404,'Interface not found');await q(env,'UPDATE interfaces SET name=?,model=?,protocol=?,mapping=?,active=?,token_hash=? WHERE id=?',String(b.name).slice(0,100),String(b.model).slice(0,100),b.protocol,mapping,b.active===false?0:1,hash,iid).run()}else await q(env,'INSERT INTO interfaces(id,name,model,protocol,token_hash,mapping,active,created) VALUES(?,?,?,?,?,?,1,?)',iid,String(b.name).slice(0,100),String(b.model).slice(0,100),b.protocol,hash,mapping,now()).run();await audit(env,user,'Analyzer interface configured: '+iid);return json({id:iid,token,endpoint:'/api/devices/'+iid+'/messages',configurationEndpoint:'/api/devices/'+iid+'/configuration'})}
if(path==='/api/messages'&&req.method==='GET'){requirePermission(user,'importResults');return json({messages:(await q(env,'SELECT m.*,i.name AS interface_name FROM messages m JOIN interfaces i ON i.id=m.interface_id ORDER BY m.created DESC LIMIT 100').all()).results.map(x=>({...x,payload:JSON.parse(x.payload)}))})}
const apply=path.match(/^\/api\/messages\/([^/]+)\/apply$/);if(apply&&req.method==='POST'){requirePermission(user,'importResults');const b=await body(req,10000),m=await q(env,'SELECT m.*,i.mapping FROM messages m JOIN interfaces i ON i.id=m.interface_id WHERE m.id=?',apply[1]).first();if(!m||m.status!=='pending')fail(409,'Message is missing or already imported');const s=await state(env,{collection:'orders',orderId:b.orderId});if(s.revision!==b.revision)fail(409,'Reload the workspace before importing');const o=s.data.orders.find(o=>o.id===b.orderId);if(!o||!o.template||o.reviewed||!o.received)fail(422,'Choose a received, unreviewed order with a result template');if(![o.id,o.requestId,String(o.sequenceNumber)].includes(m.sample_id))fail(422,'Sample identifier does not match this accession or request');const mapping=deviceSettings(m.mapping).mapping,payload=JSON.parse(m.payload);let rows=o.resultRows||o.template.fields.map(f=>({name:f.name,type:f.type,value:'',state:'Result',unit:f.unit||'',reference:f.reference||'',flag:''}));let matched=0;for(const r of payload.results){const map=mapping[r.code];if(!map)fail(422,'Unmapped device code: '+r.code);if(map.testId!==o.testId)continue;const index=o.template.fields.findIndex(f=>f.name===map.parameter);if(index<0)fail(422,'Mapped parameter is not in the order template');if(r.unit!==map.unit||rows[index].unit!==map.unit)fail(422,'Unit mismatch for '+r.code+'; no unit conversion is performed');if(rows[index].value)fail(409,'Existing results must not be overwritten: '+map.parameter);if(o.template.fields[index].type==='number'&&!/^(?:[<>]=?|[≤≥])?\s*-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(r.value))fail(422,'Invalid numeric value for '+r.code);rows[index]={...rows[index],value:r.value,state:'Result',flag:'',sourceCode:r.code,sourceMessageId:m.id};matched++}if(!matched)fail(422,'No mapped observations match this test');o.resultRows=rows;o.result=rows.filter(r=>r.value).length+' / '+rows.length+' fields recorded';o.method='Analyzer import: '+m.interface_id;o.resultAt=now();o.reviewed=false;const base=await state(env,{collection:'orders',orderId:b.orderId});const result=await storeState(env,user,{revision:s.revision,data:s.data},base);const complete=payload.results.every(r=>s.data.orders.some(x=>x.testId===mapping[r.code]?.testId&&x.resultRows?.some(z=>z.sourceMessageId===m.id&&z.sourceCode===r.code)));if(complete)await q(env,'UPDATE messages SET status=? WHERE id=?','imported',m.id).run();await audit(env,user,'Analyzer results imported as draft: '+m.id+' → '+o.id);return json(visibleState(user,result))}
fail(404,'Endpoint not found')}
const decodedImages=new Map();
function publicImageResponse(req,path){const asset=typeof PUBLIC_IMAGES!=='undefined'&&PUBLIC_IMAGES[path];if(!asset)return new Response('Not found',{status:404});const headers={'Content-Type':asset.type,'Cache-Control':'public, max-age=31536000, immutable','ETag':'"'+path+'"','X-Content-Type-Options':'nosniff'};if(req.headers.get('if-none-match')===headers.ETag)return new Response(null,{status:304,headers});if(req.method==='HEAD')return new Response(null,{headers});if(req.method!=='GET')return new Response(null,{status:405});if(!decodedImages.has(path))decodedImages.set(path,Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)));return new Response(decodedImages.get(path),{headers});}
export default {async fetch(req,env){try{const path=new URL(req.url).pathname;if(path.startsWith('/assets/'))return publicImageResponse(req,path);if(path==='/downloads/device-gateway.mjs'&&req.method==='GET')return new Response(DEVICE_GATEWAY_SOURCE,{headers:{'Content-Type':'text/javascript; charset=utf-8','Content-Disposition':'attachment; filename="device-gateway.mjs"','X-Content-Type-Options':'nosniff'}});if(path==='/sw.js')return new Response(SERVICE_WORKER,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-cache','Service-Worker-Allowed':'/','X-Content-Type-Options':'nosniff'}});if(path.startsWith('/api/')){const db=await selectDatabase(env);if(path==='/api/admin/migrate'&&req.method==='POST'){sameOrigin(req);const u=await identity(req,db.env);if(!u.owner)fail(403,'Only the owner can migrate storage');return json(await migrateDatabase(env,db.pg))}if(!db.ready&&req.method!=='GET')fail(503,'Database migration in progress. Your input is preserved; retry shortly.');return await routes(req,db.env);} if(path==='/health')return json({status:'ok',service:'CLabs'});return new Response(HTML,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}})}catch(e){if(!e.status)console.error('CLabs request failed',e.message);return json({error:e.status?e.message:'Service temporarily unavailable. Please retry.'},e.status||503)}}};
