const collections=['patients','orders','qc','analyzers','customTests','prices','sales','ultrasoundReports'];
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const reportFields=['patient','test','testId','template','specimen','method','clinician','collected','requestNote','result','resultRows','comment','astRows','astStandard','astVersion','attachments','examAt','indication','operator','equipment','technique','impression','recommendation'];
const fail=message=>{throw Object.assign(new Error(message),{status:422})};
export function changeNeedsReason(collection,old,next){if(!old)return false;if(!next)return true;if(collection==='patients')return ['name','dob','sex','phone'].some(k=>!equal(old[k],next[k]));if(collection==='sales')return !equal(old,next);if(collection==='ultrasoundReports')return old.reviewed||reportFields.some(k=>!equal(old[k],next[k]));if(collection==='orders'){if(old.reviewed)return true;if(next.reviewed&&!old.reviewed&&equal((old.resultRows||[]).map(r=>[r.name,r.state,r.value]),(next.resultRows||[]).map(r=>[r.name,r.state,r.value]))&&equal(old.result,next.result))return false;const priorResults=old.result||old.resultRows?.some(r=>r.value||r.state&&r.state!=='Result');return ['patient','testId','template','clinician','collected','requestNote','priority'].some(k=>!equal(old[k],next[k]))||priorResults&&reportFields.some(k=>!equal(old[k],next[k]));}return false;}
export function auditSnapshot(record){if(!record)return null;const out={};for(const [key,value]of Object.entries(record)){if(['signature','amendments','clinicalReview','reviewerEmail','changeReason','amendmentReason'].includes(key))continue;if(key==='attachments'){out.attachments=(value||[]).map(a=>({name:a.name,type:a.type,size:a.size}));continue}out[key]=value;}return out;}
export function recordChangeEvents(before,after,user,reasons={},at=new Date().toISOString()){
 if(!reasons||typeof reasons!=='object'||Array.isArray(reasons))fail('Invalid change reasons');
 const events=[];for(const collection of collections){const oldRows=new Map((before[collection]||[]).map(r=>[r.id,r])),nextRows=new Map((after[collection]||[]).map(r=>[r.id,r]));for(const id of new Set([...oldRows.keys(),...nextRows.keys()])){const old=oldRows.get(id),next=nextRows.get(id);if(equal(old,next))continue;const supplied=reasons[collection+':'+id]??(next?.changeReason!==old?.changeReason?next?.changeReason:undefined)??(next?.amendmentReason!==old?.amendmentReason?next?.amendmentReason:undefined)??'',reason=typeof supplied==='string'?supplied.trim():'';if(changeNeedsReason(collection,old,next)&&reason.length<3)fail('Enter a reason for '+(!next?'deleting':'amending')+' '+collection+' '+id+' (at least 3 characters)');if(reason.length>1000)fail('Keep change reasons within 1000 characters');const left=auditSnapshot(old),right=auditSnapshot(next),fields=[...new Set([...Object.keys(left||{}),...Object.keys(right||{})])].filter(k=>!equal(left?.[k],right?.[k]));events.push({kind:'record-change',operation:!old?'Created':!next?'Deleted':old.reviewed?'Amended':!old.reviewed&&next.reviewed?'Approved':'Updated',collection,recordId:id,recordNumber:old?.sequenceNumber??next?.sequenceNumber??id,patientId:next?.patient||old?.patient||null,staffName:user.name,staffEmail:user.email,reason:reason||(!old?'New record':!old.reviewed&&next.reviewed?'Clinical review and approval':'Routine record update'),fields,before:left,after:right,at});}}
 if(!equal(before.testConfig,after.testConfig))events.push({kind:'record-change',operation:'Updated',collection:'testConfig',recordId:'templates',staffName:user.name,staffEmail:user.email,reason:Object.entries(after.testConfig).filter(([key,value])=>!equal(before.testConfig[key],value)&&value.qcSop?.changeReason).map(([key,value])=>key+': '+value.qcSop.changeReason).join('; ')||'Template configuration updated',fields:['testConfig'],before:before.testConfig,after:after.testConfig,at});return events;
}
