const ROLES=['admin','scientist','reception','viewer'];
const initialData=()=>({patients:[],orders:[],qc:[],analyzers:[],activity:[],customTests:[],testConfig:{},prices:[],sales:[],ultrasoundReports:[]});
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const q=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function digest(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function body(req,max=2000000){const reader=req.body?.getReader();if(!reader)return{};let size=0,parts=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();fail(413,'Request too large')}parts.push(value)}let bytes=new Uint8Array(size),pos=0;for(const p of parts){bytes.set(p,pos);pos+=p.length}try{return JSON.parse(new TextDecoder().decode(bytes))}catch{fail(400,'Invalid JSON')}}
function sameOrigin(req){if(req.method==='GET'||req.method==='HEAD')return;const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)fail(403,'Cross-origin request rejected');if(req.headers.get('sec-fetch-site')==='cross-site')fail(403,'Cross-site request rejected');if(!req.headers.get('content-type')?.includes('application/json'))fail(415,'Use application/json')}
async function identity(req,env){
  const platformUid=req.headers.get('oai-authenticated-user-id');
  const platformEmail=req.headers.get('oai-authenticated-user-email');
  const manualEmail=req.headers.get('x-knox-username')?.trim();
  const manualPassword=req.headers.get('x-knox-password')||'';
  if(!manualEmail||!manualPassword)fail(401,'Enter your laboratory username and password');
  const email=manualEmail.toLowerCase();
  if(!email||(!manualEmail&&!platformUid))fail(401,'Enter your laboratory username to continue');
  const suppliedHash=manualEmail?(manualPassword?await digest(manualPassword):''):null;
  if(manualEmail&&!manualPassword)fail(401,'Enter your password to continue');
  if(email===env.KNOX_OWNER_EMAIL?.toLowerCase()){
    if(manualEmail&&(!env.KNOX_OWNER_PASSWORD_HASH||suppliedHash!==env.KNOX_OWNER_PASSWORD_HASH))fail(401,'Invalid username or password');
    return {email,name:'IT ADMIN',role:'admin',owner:true,auth:manualEmail?'manual-username':'chatgpt',passwordRequired:true}
  }
  const u=await q(env,'SELECT email,name,role,password_hash,active FROM staff WHERE email=?',email).first();
  if(!u||!u.active)fail(403,'Your username has not been granted staff access. Ask the administrator.');
  if(manualEmail&&(!u.password_hash||suppliedHash!==u.password_hash))fail(401,'Invalid username or password');
  return {email:u.email,name:u.name,role:u.role,owner:false,auth:manualEmail?'manual-username':'chatgpt',passwordRequired:true}
}
function permit(user,roles){if(!roles.includes(user.role))fail(403,'Your role does not permit this action')}
export function validateRelease(o,data){
 const text=v=>typeof v==='string'&&v.trim().length>0;
 const p=data.patients.find(p=>p.id===o.patient);
 if(!p||!text(p.name)||!text(p.dob)||!text(p.sex))fail(422,'Complete patient name, date of birth and sex before review');
 if(!o.received||!text(o.specimen)||!text(o.method))fail(422,'Receive the specimen and record the method before review');
 const a=o.clinicalReview;
 if(!a||a.identity!==true||a.qc!==true||a.references!==true||!text(a.evidence))fail(422,'Document patient identity, QC and reference interval verification with an SOP / QC record reference');
 if(!o.template?.fields?.length||!Array.isArray(o.resultRows)||o.resultRows.length!==o.template.fields.length)fail(422,'A complete structured result template is required for review');
 o.resultRows.forEach((r,i)=>{
 const f=o.template.fields[i];
 if(r.name!==f.name||!['Result','Not performed','Not applicable'].includes(r.state))fail(422,'Result fields do not match the order template');
 if(r.state!=='Result')return;
 if(!text(r.value))fail(422,'Complete result: '+f.name);
 if(f.type==='number'&&!/^(?:[<>]=?|[≤≥])?\s*-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(r.value))fail(422,'Invalid numeric result: '+f.name);
 if(f.type==='number'&&(!text(r.unit)||!text(r.reference)||/PROVISIONAL|not configured|not supplied/i.test(r.reference)))fail(422,'Supply laboratory-approved units and a patient-appropriate reference interval for '+f.name);
 if(r.flag==='Critical'&&!text(a.criticalNotification))fail(422,'Document critical-result recipient, notification time and read-back');
 });
}
async function audit(env,u,action){await q(env,'INSERT INTO audit(id,actor,action,created) VALUES(?,?,?,?)',id(),u.email,action,now()).run()}
async function state(env,scope=null,options={}){return scaledState(env,scope,options)}
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function validateState(data){if(!data||typeof data!=='object'||Array.isArray(data))fail(400,'Invalid workspace');const keys=['patients','orders','qc','analyzers','activity','customTests','prices','sales','ultrasoundReports'];for(const k of keys){if(!Array.isArray(data[k])||data[k].length>10000)fail(400,'Invalid '+k);if(k!=='activity'&&data[k].some(r=>!r||typeof r!=='object'||typeof r.id!=='string'||! /^[A-Za-z0-9_-]{1,100}$/.test(r.id)))fail(400,'Invalid record identifiers');if(k!=='activity'&&new Set(data[k].map(x=>x.id)).size!==data[k].length)fail(400,'Duplicate record identifiers')}if(!data.testConfig||Array.isArray(data.testConfig)||typeof data.testConfig!=='object')fail(400,'Invalid test configuration');for(const k of Object.keys(data))if(![...keys,'testConfig'].includes(k))fail(400,'Unknown workspace field');const pids=new Set(data.patients.map(p=>p.id));for(const o of data.orders)if(!pids.has(o.patient))fail(400,'An order references an unknown patient');for(const sale of data.sales)if(sale.patient&&!pids.has(sale.patient))fail(400,'A sale references an unknown patient')}
function authorizeChanges(user,before,after){permit(user,['admin','scientist','reception']);if(user.role==='admin')return;if(!equal(before.customTests,after.customTests)||!equal(before.testConfig,after.testConfig)||!equal(before.analyzers,after.analyzers)||!equal(before.prices,after.prices))fail(403,'Only administrators can change catalogue, analyzer or price settings');if(user.role==='reception'){if(!equal(before.qc,after.qc))fail(403,'Reception cannot edit QC');const allowed=['id','patient','patientId','priority','clinician','collected','requestNote','testId','test','department','specimen','template','created','requestId','received','reviewed'];for(const o of after.orders){const old=before.orders.find(x=>x.id===o.id);if(!old){if(o.reviewed||Object.keys(o).some(k=>!allowed.includes(k)))fail(403,'Reception cannot enter results')}else{for(const k of new Set([...Object.keys(old),...Object.keys(o)])){if(!['received','specimen','clinician','collected','requestNote','priority'].includes(k)&&!equal(old[k],o[k]))fail(403,'Reception cannot modify result data')}}}if(before.orders.some(o=>!after.orders.some(x=>x.id===o.id)))fail(403,'Reception cannot delete orders')}if(user.role==='scientist'){for(const old of before.orders.filter(o=>o.reviewed)){if(!equal(old,after.orders.find(o=>o.id===old.id)))fail(403,'Only administrators may amend reviewed results')}}}
async function storeState(env,user,payload){validateState(payload.data);const invoiced=new Set();for(const sale of payload.data.sales){if(sale.orderId&&sale.status!=='Cancelled'){if(invoiced.has(sale.orderId))fail(422,'An order cannot have duplicate active sales');invoiced.add(sale.orderId);const order=payload.data.orders.find(o=>o.id===sale.orderId);if(!order||order.patient!==sale.patient)fail(422,'Receipt patient must match the order');if(!Number.isFinite(sale.total)||sale.total<0||sale.total!==sale.quantity*sale.unitPrice)fail(422,'Invalid receipt amount')}}if(!payload.scope)fail(409,'Website updated. Copy unsaved input and refresh before saving.');const lookup=Object.fromEntries(recordCollections.map(k=>[k,[...new Set([...(payload.scope[k]||[]),...payload.data[k].map(r=>r.id)])]]));const current=await state(env,lookup);if(payload.revision!==current.revision)fail(409,'Another staff member changed the workspace. Reload shared records before saving again. Your unsaved changes remain visible.');authorizeChanges(user,current.data,payload.data);for(const o of payload.data.orders){const prev=current.data.orders.find(x=>x.id===o.id);const orderChanged=!equal(o,prev);o.patientId=o.patient;if(o.signature&&(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(o.signature)||o.signature.length>200000))fail(422,'Invalid signature image');if(o.reviewed&&(!prev?.reviewed||orderChanged)){validateRelease(o,payload.data);o.reviewer=user.name;o.reviewerEmail=user.email;o.resultAt=now();o.clinicalReview.verifiedBy=user.email;o.clinicalReview.verifiedAt=o.resultAt}}
return persistRecordState(env,user,payload,current)}

export function parseHL7(raw){if(typeof raw!=='string'||raw.length>200000)fail(400,'Invalid HL7 payload');raw=raw.replace(/^\x0b/,'').replace(/\x1c\r?$/,'');const segments=raw.split(/\r\n|\r|\n/).filter(Boolean).map(s=>s.split('|'));const msh=segments[0];if(msh?.[0]!=='MSH'||msh[1]!=='^~\\&'||!msh[8]?.startsWith('ORU^R01'))fail(422,'Only HL7 ORU^R01 with standard separators is supported by this adapter');const obr=segments.filter(s=>s[0]==='OBR');if(obr.length!==1)fail(422,'Send exactly one OBR sample per message');const messageId=msh[9],sampleId=(obr[0][3]||obr[0][2]||'').split('^')[0];const results=segments.filter(s=>s[0]==='OBX').map(s=>{if(!['NM','ST','SN'].includes(s[2]))fail(422,'Unsupported OBX value type');if(!['F','C'].includes(s[11]))fail(422,'Only final or corrected observations are accepted into the review inbox');if(/[~\\]/.test(s[5]||''))fail(422,'Repeated or escaped OBX values require a model-specific adapter');if(s[2]==='SN')fail(422,'Structured numeric values require model-specific normalization');return {code:(s[3]||'').split('^')[0],value:s[5],unit:(s[6]||'').split('^')[0],reference:s[7]||'',flag:s[8]||''}});return {messageId,sampleId,results}}
function validateMessage(p){if(typeof p.messageId!=='string'||!p.messageId||p.messageId.length>160||typeof p.sampleId!=='string'||!p.sampleId||p.sampleId.length>160||!Array.isArray(p.results)||!p.results.length||p.results.length>300)fail(400,'messageId, sampleId and 1–300 results are required');for(const r of p.results){if(typeof r.code!=='string'||!r.code||typeof r.value!=='string'||!r.value||r.value.length>1000||typeof r.unit!=='string')fail(400,'Each result needs code, string value and unit');}if(new Set(p.results.map(r=>r.code)).size!==p.results.length)fail(422,'Duplicate observation codes need model-specific normalization')}
async function ingest(req,env,interfaceId){const it=await q(env,'SELECT * FROM interfaces WHERE id=? AND active=1',interfaceId).first();if(!it)fail(401,'Invalid interface credentials');const token=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(!token||await digest(token)!==it.token_hash)fail(401,'Invalid interface credentials');const b=await body(req,250000);if((it.protocol==='HL7')!==(b.format==='hl7'))fail(422,'Payload does not match the configured adapter');const p=b.format==='hl7'?parseHL7(b.raw):b;validateMessage(p);const existing=await q(env,'SELECT id,payload FROM messages WHERE interface_id=? AND message_id=?',it.id,p.messageId).first();if(existing){if(!equal(JSON.parse(existing.payload),p))fail(409,'Message ID was reused with different content');return json({accepted:true,duplicate:true,id:existing.id})}const mid=id();await env.DB.batch([q(env,'INSERT INTO messages(id,interface_id,message_id,sample_id,payload,status,created) VALUES(?,?,?,?,?,?,?)',mid,it.id,p.messageId,p.sampleId,JSON.stringify(p),'pending',now()),q(env,'UPDATE interfaces SET last_seen=? WHERE id=?',now(),it.id)]);return json({accepted:true,id:mid,status:'pending_review'},202)}
async function routes(req,env){const path=new URL(req.url).pathname;const incoming=path.match(/^\/api\/mindray\/([^/]+)\/messages$/);if(incoming&&req.method==='POST')return ingest(req,env,incoming[1]);sameOrigin(req);const user=await identity(req,env);
if(path==='/api/me')return json({user});
if(path==='/api/state'&&req.method==='GET')return json(await state(env,null,Object.fromEntries(new URL(req.url).searchParams)));
if(path==='/api/state'&&req.method==='PUT')return json(await storeState(env,user,await body(req)));
if(path==='/api/staff'&&req.method==='GET'){permit(user,['admin']);const r=await q(env,'SELECT email,name,role,active,created FROM staff ORDER BY name').all();return json({staff:[{email:env.KNOX_OWNER_EMAIL,name:'IT ADMIN',role:'admin',active:1,owner:true},...r.results.filter(u=>u.email!==env.KNOX_OWNER_EMAIL)]})}
if(path==='/api/staff'&&req.method==='POST'){permit(user,['admin']);const b=await body(req,10000),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||'');if(!/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(email)||!name||name.length>100||!ROLES.includes(b.role))fail(400,'Enter a valid email, name and role');if(email===env.KNOX_OWNER_EMAIL)fail(400,'The owner administrator cannot be changed here');if(password&&password.length<8)fail(400,'Passwords must be at least 8 characters');const existing=await q(env,'SELECT password_hash FROM staff WHERE email=?',email).first();if(!existing&&!password)fail(400,'A password is required for new staff');const passwordHash=password?await digest(password):existing?.password_hash||null;if(existing)await q(env,'UPDATE staff SET name=?,role=?,password_hash=?,active=? WHERE email=?',name,b.role,passwordHash,b.active===false?0:1,email).run();else await q(env,'INSERT INTO staff(email,name,role,password_hash,active,created) VALUES(?,?,?,?,?,?)',email,name,b.role,passwordHash,b.active===false?0:1,now()).run();await audit(env,user,'Staff access updated: '+email+' / '+b.role);return json({ok:true})}
if(path==='/api/audit'&&req.method==='GET'){permit(user,['admin']);return json({events:(await q(env,'SELECT actor,action,created FROM audit ORDER BY created DESC LIMIT 100').all()).results})}
if(path==='/api/interfaces'&&req.method==='GET'){permit(user,['admin','scientist']);return json({interfaces:(await q(env,'SELECT id,name,model,protocol,active,mapping,last_seen,created FROM interfaces ORDER BY created DESC').all()).results.map(x=>({...x,mapping:JSON.parse(x.mapping)}))})}
if(path==='/api/interfaces'&&req.method==='POST'){permit(user,['admin']);const b=await body(req,100000);if(!b.name||!b.model||!['JSON','HL7'].includes(b.protocol))fail(400,'Specify a name, model and supported adapter');let mapping=b.mapping||{};if(typeof mapping!=='object'||Array.isArray(mapping))fail(400,'Mapping must be an object');for(const [code,m]of Object.entries(mapping)){if(!code||typeof m.parameter!=='string'||typeof m.testId!=='string'||typeof m.unit!=='string')fail(400,'Each map entry needs testId, parameter and unit')}const token='knox_'+crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),iid=b.id||id(),hash=await digest(token);if(b.id){const exists=await q(env,'SELECT id FROM interfaces WHERE id=?',iid).first();if(!exists)fail(404,'Interface not found');await q(env,'UPDATE interfaces SET name=?,model=?,protocol=?,mapping=?,active=?,token_hash=? WHERE id=?',String(b.name).slice(0,100),String(b.model).slice(0,100),b.protocol,JSON.stringify(mapping),b.active===false?0:1,hash,iid).run()}else await q(env,'INSERT INTO interfaces(id,name,model,protocol,token_hash,mapping,active,created) VALUES(?,?,?,?,?,?,1,?)',iid,String(b.name).slice(0,100),String(b.model).slice(0,100),b.protocol,hash,JSON.stringify(mapping),now()).run();await audit(env,user,'Analyzer interface configured: '+iid);return json({id:iid,token,endpoint:'/api/mindray/'+iid+'/messages'})}
if(path==='/api/messages'&&req.method==='GET'){permit(user,['admin','scientist']);return json({messages:(await q(env,'SELECT m.*,i.name AS interface_name FROM messages m JOIN interfaces i ON i.id=m.interface_id ORDER BY m.created DESC LIMIT 100').all()).results.map(x=>({...x,payload:JSON.parse(x.payload)}))})}
const apply=path.match(/^\/api\/messages\/([^/]+)\/apply$/);if(apply&&req.method==='POST'){permit(user,['admin','scientist']);const b=await body(req,10000),m=await q(env,'SELECT m.*,i.mapping FROM messages m JOIN interfaces i ON i.id=m.interface_id WHERE m.id=?',apply[1]).first();if(!m||m.status!=='pending')fail(409,'Message is missing or already imported');const s=await state(env);if(s.revision!==b.revision)fail(409,'Reload the workspace before importing');const o=s.data.orders.find(o=>o.id===b.orderId);if(!o||!o.template||o.reviewed||!o.received)fail(422,'Choose a received, unreviewed order with a result template');if(![o.id,o.requestId].includes(m.sample_id))fail(422,'Sample identifier does not match this accession or request');const mapping=JSON.parse(m.mapping),payload=JSON.parse(m.payload);let rows=o.resultRows||o.template.fields.map(f=>({name:f.name,type:f.type,value:'',state:'Result',unit:f.unit||'',reference:f.reference||'',flag:''}));let matched=0;for(const r of payload.results){const map=mapping[r.code];if(!map)fail(422,'Unmapped device code: '+r.code);if(map.testId!==o.testId)continue;const index=o.template.fields.findIndex(f=>f.name===map.parameter);if(index<0)fail(422,'Mapped parameter is not in the order template');if(r.unit!==map.unit||rows[index].unit!==map.unit)fail(422,'Unit mismatch for '+r.code+'; no unit conversion is performed');if(rows[index].value)fail(409,'Existing results must not be overwritten: '+map.parameter);if(o.template.fields[index].type==='number'&&!/^(?:[<>]=?|[≤≥])?\s*-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(r.value))fail(422,'Invalid numeric value for '+r.code);rows[index]={...rows[index],value:r.value,state:'Result',flag:'',sourceCode:r.code,sourceMessageId:m.id};matched++}if(!matched)fail(422,'No mapped observations match this test');o.resultRows=rows;o.result=rows.filter(r=>r.value).length+' / '+rows.length+' fields recorded';o.method='Analyzer import: '+m.interface_id;o.resultAt=now();o.reviewed=false;const result=await storeState(env,user,{revision:s.revision,data:s.data,scope:s.scope});const complete=payload.results.every(r=>s.data.orders.some(x=>x.testId===mapping[r.code]?.testId&&x.resultRows?.some(z=>z.sourceMessageId===m.id&&z.sourceCode===r.code)));if(complete)await q(env,'UPDATE messages SET status=? WHERE id=?','imported',m.id).run();await audit(env,user,'Analyzer results imported as draft: '+m.id+' → '+o.id);return json(result)}
fail(404,'Endpoint not found')}
export default {async fetch(req,env){try{const path=new URL(req.url).pathname;if(path.startsWith('/api/'))return await routes(req,env);if(path==='/health')return json({status:'ok',service:'CLabs'});return new Response(HTML,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}})}catch(e){if(!e.status)console.error('CLabs request failed',e.message);return json({error:e.status?e.message:'Service temporarily unavailable. Please retry.'},e.status||503)}}};

const recordCollections=['patients','orders','qc','analyzers','customTests','prices','sales','ultrasoundReports'];
const makeScope=data=>Object.fromEntries(recordCollections.map(k=>[k,data[k].map(r=>r.id)]));
async function ensureRecordStorage(env){
 if(await q(env,'SELECT id FROM storage_meta WHERE id=1').first())return;
 await q(env,'INSERT INTO workspace(id,revision,data) VALUES(1,0,?) ON CONFLICT(id) DO NOTHING',JSON.stringify(initialData())).run();
 const commands=recordCollections.map(k=>q(env,`INSERT OR IGNORE INTO clinical_records(key,collection,record_id,patient_id,search_name,data,updated) SELECT ? || ':' || json_extract(j.value,'$.id'),?,json_extract(j.value,'$.id'),json_extract(j.value,'$.patient'),lower(coalesce(json_extract(j.value,'$.name'),json_extract(j.value,'$.test'),'')),j.value,? FROM workspace w,json_each(w.data,?) j WHERE w.id=1 AND NOT EXISTS(SELECT 1 FROM storage_meta WHERE id=1)`,k,k,now(),'$.'+k));
 commands.push(q(env,"INSERT OR IGNORE INTO storage_meta(id,revision,settings,activity) SELECT 1,revision,coalesce(json_extract(data,'$.testConfig'),'{}'),coalesce(json_extract(data,'$.activity'),'[]') FROM workspace WHERE id=1"));
 commands.push(q(env,'INSERT OR IGNORE INTO storage_guard(id,revision) VALUES(1,0)'));
 await env.DB.batch(commands);
}
async function scaledState(env,scope=null,options={}){
 await ensureRecordStorage(env);
 const commands=[q(env,'SELECT revision,settings,activity FROM storage_meta WHERE id=1')];
 for(const k of recordCollections){
  if(scope){const ids=scope[k]||[];if(!Array.isArray(ids)||ids.length>1500||ids.some(id=>typeof id!=='string'))fail(400,'Invalid record scope');commands.push(q(env,'SELECT data FROM clinical_records WHERE collection=? AND record_id IN (SELECT value FROM json_each(?)) ORDER BY updated DESC,record_id',k,JSON.stringify(ids)));continue}
  let sql='SELECT data FROM clinical_records WHERE collection=?',args=[k];
  if(options.collection===k){if(options.patientId){sql+=' AND patient_id=?';args.push(options.patientId)}if(options.requestId){sql+=" AND json_extract(data,'$.requestId')=?";args.push(options.requestId)}if(options.query){sql+=' AND (search_name>=? AND search_name<? OR record_id=?)';args.push(options.query.toLowerCase(),options.query.toLowerCase()+'\uffff',options.query)}if(options.after){sql+=' AND record_id>?';args.push(options.after)}sql+=' ORDER BY record_id LIMIT 101'}
  else sql+=' ORDER BY record_id LIMIT '+(['customTests','prices','analyzers'].includes(k)?1500:51);
  commands.push(q(env,sql,...args));
 }
 const result=await env.DB.batch(commands),meta=result[0].results[0],data=initialData(),pagination={};
 for(let i=0;i<recordCollections.length;i++){const k=recordCollections[i],rows=result[i+1].results.map(r=>JSON.parse(r.data));const limit=options.collection===k?100:['customTests','prices','analyzers'].includes(k)?1500:50;data[k]=scope?rows:rows.slice(0,limit);pagination[k]=!scope&&rows.length>limit?data[k].at(-1).id:null}
 data.testConfig=JSON.parse(meta.settings);data.activity=JSON.parse(meta.activity);
 const ids=[...new Set([...data.orders,...data.sales,...data.ultrasoundReports].map(r=>r.patient).filter(Boolean))].filter(id=>!data.patients.some(p=>p.id===id));
 if(ids.length){const refs=await q(env,"SELECT data FROM clinical_records WHERE collection='patients' AND record_id IN (SELECT value FROM json_each(?))",JSON.stringify(ids)).all();data.patients.push(...refs.results.map(r=>JSON.parse(r.data)))}
 const end=await q(env,'SELECT revision FROM storage_meta WHERE id=1').first();if(end.revision!==meta.revision)fail(409,'Records changed while loading. Please reload.');
 return {revision:meta.revision,data,scope:makeScope(data),pagination,storageVersion:2};
}
async function persistRecordState(env,user,payload,current){
 const commands=[q(env,'UPDATE storage_guard SET revision=(SELECT revision+1 FROM storage_meta WHERE id=1 AND revision=?) WHERE id=1',payload.revision)];
 for(const k of recordCollections){const old=new Map(current.data[k].map(r=>[r.id,r])),next=new Map(payload.data[k].map(r=>[r.id,r]));
  for(const record of payload.data[k]){if(equal(record,old.get(record.id)))continue;const bytes=JSON.stringify(record);if(new TextEncoder().encode(bytes).length>1500000)fail(413,'Record too large. Store large attachments in cloud file storage.');commands.push(q(env,'INSERT INTO clinical_records(key,collection,record_id,patient_id,search_name,data,updated) VALUES(?,?,?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET patient_id=excluded.patient_id,search_name=excluded.search_name,data=excluded.data,updated=excluded.updated',k+':'+record.id,k,record.id,record.patient||null,String(record.name||record.test||'').toLowerCase(),bytes,now()))}
  for(const record of current.data[k])if((payload.scope[k]||[]).includes(record.id)&&!next.has(record.id)){
   if(k==='patients'){const linked=await q(env,"SELECT key FROM clinical_records WHERE patient_id=? LIMIT 1",record.id).first();if(linked)fail(422,'Patient has clinical or financial records and cannot be deleted')}
   if(k==='orders'){const linked=await q(env,"SELECT key FROM clinical_records WHERE collection='sales' AND json_extract(data,'$.orderId')=? LIMIT 1",record.id).first();if(linked)fail(422,'Order has financial records and cannot be deleted')}
   commands.push(q(env,'DELETE FROM clinical_records WHERE key=?',k+':'+record.id));
  }
 }
 commands.push(q(env,'UPDATE storage_meta SET revision=revision+1,settings=?,activity=? WHERE id=1',JSON.stringify(payload.data.testConfig),JSON.stringify(payload.data.activity.slice(0,20))));
 commands.push(q(env,'INSERT INTO audit(id,actor,action,created) VALUES(?,?,?,?)',id(),user.email,'Saved scoped laboratory records (revision '+(payload.revision+1)+')',now()));
 if(commands.length>500)fail(413,'Too many simultaneous edits. Save smaller batches.');
 try{await env.DB.batch(commands)}catch(e){if(String(e.message).includes('NOT NULL'))fail(409,'Another staff member saved changes. Reload before saving.');throw e}
 return {revision:payload.revision+1,data:payload.data,scope:makeScope(payload.data),storageVersion:2};
}
