import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const staff=sqliteTable('staff',{email:text('email').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),passwordHash:text('password_hash'),active:integer('active').notNull().default(1),created:text('created').notNull()});
export const workspace=sqliteTable('workspace',{id:integer('id').primaryKey(),revision:integer('revision').notNull().default(0),data:text('data').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),created:text('created').notNull()});
export const interfaces=sqliteTable('interfaces',{id:text('id').primaryKey(),name:text('name').notNull(),model:text('model').notNull(),protocol:text('protocol').notNull(),tokenHash:text('token_hash').notNull(),active:integer('active').notNull().default(1),mapping:text('mapping').notNull(),lastSeen:text('last_seen'),created:text('created').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),interfaceId:text('interface_id').notNull(),messageId:text('message_id').notNull(),sampleId:text('sample_id').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),created:text('created').notNull()},t=>[uniqueIndex('messages_interface_message').on(t.interfaceId,t.messageId)]);
export const clinicalRecords=sqliteTable('clinical_records',{key:text('key').primaryKey(),collection:text('collection').notNull(),recordId:text('record_id').notNull(),patientId:text('patient_id'),searchName:text('search_name').notNull().default(''),data:text('data').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('clinical_collection_id').on(t.collection,t.recordId),index('clinical_patient_lookup').on(t.collection,t.patientId,t.recordId),index('clinical_name_lookup').on(t.collection,t.searchName,t.recordId)]);
export const storageMeta=sqliteTable('storage_meta',{id:integer('id').primaryKey(),revision:integer('revision').notNull(),settings:text('settings').notNull(),activity:text('activity').notNull()});
export const storageGuard=sqliteTable('storage_guard',{id:integer('id').primaryKey(),revision:integer('revision').notNull()});
