let pendingAuditReasons={};
const auditApi=api;api=async function(path,method='GET',payload){if(path==='/api/state'&&method==='PUT')payload={...payload,changeReasons:{...pendingAuditReasons,...payload.changeReasons}};const result=await auditApi(path,method,payload);if(path==='/api/state'&&method==='PUT')pendingAuditReasons={};return result;};
function reasonField(){return '<label class="full">Reason for change<textarea name="changeReason" rows="3" minlength="3" maxlength="1000" required placeholder="Explain why this correction is needed"></textarea></label>'}
function auditReasonForm(record,resultEdit=false){const f=document.getElementById('form');if(!f||!document.getElementById('modal').open||f.querySelector('[name="changeReason"],[name="amendmentReason"]'))return;f.querySelector('.fields').insertAdjacentHTML('beforeend',reasonField());const reasonInput=f.querySelector('[name="changeReason"]');const contentSnapshot=()=>JSON.stringify([...new FormData(f)].filter(([key])=>/^(v_|state_|unit_|ref_|flag_|isolate_|agent_|mic_|zone_|ast_)/.test(key)||['specimen','method','comment','astStandard','astVersion'].includes(key)));const initial=contentSnapshot();const needsReason=()=>!resultEdit||contentSnapshot()!==initial||!!f.querySelector('[name="attachment"]')?.files?.length;const refreshReason=()=>{const required=needsReason();reasonInput.required=required;reasonInput.closest('label').hidden=!required};if(resultEdit){refreshReason();f.addEventListener('input',refreshReason);f.addEventListener('change',refreshReason)}const submit=f.onsubmit;f.onsubmit=async event=>{event.preventDefault();const reason=String(new FormData(f).get('changeReason')||'').trim();if(needsReason()&&reason.length<3)return notify('Enter a reason of at least 3 characters.'),false;if(needsReason()){record.changeReason=reason;const collection=['patients','orders','ultrasoundReports'].find(k=>db[k].includes(record));if(collection)pendingAuditReasons[collection+':'+record.id]=reason}return submit(event)};}
for(const [name,collection] of [['editPatient','patients'],['editOrder','orders'],['resultForm','orders']]){const previous=window[name];window[name]=function(id,...args){const record=db[collection].find(r=>r.id===id);previous(id,...args);if(record&&(name!=='resultForm'||record.result||record.resultRows?.some(r=>r.value||r.state&&r.state!=='Result')))auditReasonForm(record,name==='resultForm')}}
const auditUltrasoundForm=ultrasoundForm;ultrasoundForm=function(id,...args){auditUltrasoundForm(id,...args);const record=db.ultrasoundReports.find(r=>r.id===id);if(record&&!record.reviewed)auditReasonForm(record)};
function confirmRecordDeletion(collection,id){
 if(!can(currentUser,'delete'))return notify('Delete permission required.');if(!db[collection])return;const record=db[collection].find(r=>r.id===id);if(!record)return;
 if(collection==='ultrasoundReports'&&(!ultrasoundAllowed('ultrasoundView')||!ultrasoundAllowed('ultrasoundEnter')||record.reviewed))return notify('Final scans must be amended; draft deletion requires ultrasound privileges.');
 if(collection==='patients'&&[...db.orders,...db.ultrasoundReports,...db.sales].some(r=>r.patient===id))return notify('This patient has linked records and cannot be deleted.');
 modal('Delete record', '<p class="full"><b>'+esc(record.name||record.test||collection)+'</b> · Record '+esc(displayNumber(record))+'</p>'+reasonField(),async v=>{const reason=String(v.changeReason||'').trim();if(reason.length<3)return notify('Enter a reason of at least 3 characters.'),false;const prior=[...db[collection]],wasUnsaved=unsaved;pendingAuditReasons[collection+':'+id]=reason;db[collection]=db[collection].filter(r=>r.id!==id);const ok=await save('Record deletion saved with its reason');if(!ok){db[collection]=prior;unsaved=wasUnsaved;delete pendingAuditReasons[collection+':'+id]}return ok},'Delete record');
}
deleteRecord=confirmRecordDeletion;deleteSale=id=>confirmRecordDeletion('sales',id);deleteUltrasound=id=>confirmRecordDeletion('ultrasoundReports',id);
amendResult=function(id){if(!can(currentUser,'amend'))return notify('Amendment permission required.');const order=db.orders.find(o=>o.id===id);if(!order)return;if(!order.reviewed){resultForm(id);return}modal('Amend result',reasonField(),async v=>{const reason=String(v.changeReason||'').trim();if(reason.length<3)return false;const previous=structuredClone(order);order.changeReason=reason;pendingAuditReasons['orders:'+id]=reason;order.amendments=[...(order.amendments||[]),{reason,previousRows:order.resultRows||null,previousResult:order.result,previousReviewer:order.reviewer,time:new Date().toISOString()}];order.reviewed=false;const ok=await save('Result reopened with amendment reason');if(!ok){Object.assign(order,previous);return false}closeModal();resultForm(id);return false},'Continue amendment');};
let auditPageSequence=0;
function renderAdminAudit(){document.getElementById('app').innerHTML=head('Admin change log','Deletions, amendments and report history · GMT',btn('Refresh','loadAdminAudit()'))+'<div id="auditList" class="card padded">Loading change log…</div>';void loadAdminAudit()}
async function loadAdminAudit(after=''){if(currentUser?.role!=='admin')return;const sequence=++auditPageSequence,session=workspaceSession;try{const data=await api('/api/audit'+(after?'?after='+encodeURIComponent(after):''));if(page!=='Audit log'||session!==workspaceSession||sequence!==auditPageSequence)return;document.getElementById('auditList').innerHTML=table(['Time (GMT)','Staff','Action / record','Reason','Changes'],data.events.map(e=>{let d;try{d=JSON.parse(e.action)}catch{}if(d?.kind!=='record-change')return '<tr><td>'+esc(e.created)+'</td><td>'+esc(e.actor)+'</td><td colspan="3">'+esc(e.action)+'</td></tr>';return '<tr><td>'+esc(e.created)+'</td><td>'+esc(d.staffName)+'<small>'+esc(e.actor)+'</small></td><td>'+esc(d.operation)+'<small>'+esc(d.collection)+' · '+esc(d.recordNumber||d.recordId)+'</small></td><td style="white-space:normal;max-width:260px">'+esc(d.reason)+'</td><td><details><summary>'+esc(d.fields.join(', ')||'Record')+'</summary><div style="max-width:420px;white-space:normal"><b>Before</b><pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(JSON.stringify(d.before,null,2))+'</pre><b>After</b><pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(JSON.stringify(d.after,null,2))+'</pre></div></details></td></tr>'}),'No changes recorded.')+'<div class="spacer">'+btn('Latest changes','loadAdminAudit()')+(data.next?' '+btn('Older changes',"loadAdminAudit('"+data.next+"')"):'')+'</div>'}catch(e){if(page==='Audit log'&&sequence===auditPageSequence)document.getElementById('auditList').textContent=e.message;}}
const auditSignOut=manualSignOut;manualSignOut=function(){pendingAuditReasons={};auditPageSequence++;return auditSignOut()};
