// ECG uses the shared order store, sequential accession numbers and release controls.
pages.push('Electrocardiogram');
if(location.hash==='#Electrocardiogram'&&page==='Overview')page='Electrocardiogram';
addTest('ECG12','12-lead Electrocardiogram','Electrocardiogram','ECG trace',[
 ['Ventricular rate','bpm','number'],['Atrial rate','bpm','number'],['Rhythm','','narrative'],['QRS axis','°','number'],['P-wave morphology','','narrative'],['PR interval','ms','number'],['QRS duration','ms','number'],['QRS morphology / chamber abnormality','','narrative'],['QT interval','ms','number'],['QTc interval','ms','number'],['QTc correction method','','text'],['ST segments','','narrative'],['T waves','','narrative'],['Other findings','','narrative'],['Conclusion','','narrative'],['Recommendations','','narrative']
].map(([name,unit,type])=>({name,unit,type,reference:''})), 'ECG');
function ecgPage(){
 const rows=db.orders.filter(o=>o.testId==='ECG12').map(o=>'<tr><td><b>'+esc(patient(o.patient)?.name)+'</b><small>Patient ID '+esc(patientNumber(o.patient))+'</small></td><td>'+esc(displayNumber(o))+'</td><td>'+esc(date(o.collected||o.created))+'</td><td>'+badge(o.reviewed?'Reviewed':o.resultRows?.length?'Draft':o.received?'Recorded':'Awaiting recording')+'</td><td>'+(!o.received&&can(currentUser,'specimens')?btn('Confirm recording',"receive('"+o.id+"')"):'')+(o.received&&!o.reviewed&&can(currentUser,'results')?btn('Enter findings',"resultForm('"+o.id+"')"):'')+(o.reviewed?btn('View / Print',"showReport('"+o.id+"')"):'')+(o.reviewed&&can(currentUser,'amend')?btn('Amend',"amendResult('"+o.id+"')"):'')+'</td></tr>');
 return head('Electrocardiogram','12-lead ECG recordings and reports · GMT',can(currentUser,'orders')?btn('＋ New ECG recording','ecgForm()',true):'')+'<section class="card">'+table(['Patient','Accession','Recorded (GMT)','Status','Actions'],rows,'No ECG recordings on this page.')+'</section><section class="card padded spacer"><h2>ECG result template</h2><p>Rate and rhythm · axis · PR, QRS, QT and QTc intervals · waveform findings · conclusion and recommendations.</p>'+(can(currentUser,'catalogue')?btn('Edit template',"templateForm('ECG12')"):'')+'</section>';
}
function ecgForm(){
 if(!can(currentUser,'orders'))return notify('Order permission required.');
 if(!db.patients.length){navTo('Patients');patientForm();return}
 modal('New Electrocardiogram recording',select('patient','Patient',db.patients.map(p=>[p.id,p.name+' · '+displayNumber(p)]))+'<div class="full"><label>Search all registered patients<input id="ecgPatientSearch" placeholder="Name starts with or exact patient ID"></label><button type="button" class="btn" onclick="searchOrderPatients(document.getElementById(\'ecgPatientSearch\').value)">Find patient</button></div>'+field('collected','Recording date / time (GMT)','datetime-local',true,new Date().toISOString().slice(0,16))+field('clinician','Requesting clinician','text',false)+field('equipment','ECG machine / method','text',true,'12-lead resting ECG')+field('operator','Performing staff','text',true,currentUser.name)+'<label class="full">Clinical indication<textarea name="requestNote" rows="3" maxlength="1000"></textarea></label>'+(can(currentUser,'specimens')?'<label class="full checkline"><input name="recorded" type="checkbox"> Recording completed and patient identity confirmed</label>':''),async v=>{
  const t=testById('ECG12'),o={id:uid('ECG'),requestId:uid('REQ'),patient:v.patient,patientId:v.patient,priority:'Routine',clinician:v.clinician,collected:v.collected,requestNote:v.requestNote,testId:t.id,test:t.name,department:t.department,specimen:'ECG trace',method:v.equipment,operator:v.operator,template:snapshot(t),created:new Date().toISOString(),received:!!v.recorded,reviewed:false};db.orders.unshift(o);log('ECG recording created');const ok=await save('ECG recording saved');if(!ok)db.orders=db.orders.filter(x=>x.id!==o.id);return ok;
 },'Save recording');makeWide();
}
const ecgOrderForm=orderForm;orderForm=function(id,preselect){if(preselect==='ECG12'){navTo('Electrocardiogram');return ecgForm()}return ecgOrderForm(id,preselect)};
const ecgRender=render;render=function(){ecgRender();if(currentUser&&page==='Electrocardiogram'){document.getElementById('app').innerHTML=ecgPage();recordPageControls();}};
const ecgResultForm=resultForm;resultForm=function(id){ecgResultForm(id);const o=db.orders.find(x=>x.id===id);if(o?.testId!=='ECG12'||o.reviewed)return;const f=document.getElementById('form');if(!f||!document.getElementById('modal').open)return;for(const p of f.querySelectorAll('.help'))if(/Provisional ranges|Before approval/.test(p.textContent))p.textContent='Complete findings or mark them not assessed. A qualified reviewer must verify the ECG interpretation.';const check=f.querySelector('[name="verify_qc"]');if(check)check.parentElement.lastChild.textContent=' Recording quality, calibration and technique verified';const refs=f.querySelector('[name="verify_references"]');if(refs)refs.parentElement.lastChild.textContent=' Measurements, units and clinical interpretation verified';};
const ecgShowReport=showReport;showReport=function(id){const o=db.orders.find(x=>x.id===id);if(o?.testId!=='ECG12')return ecgShowReport(id);if(unsaved)return notify('Save successfully before opening reports.');if(!o.reviewed)return;document.getElementById('app').innerHTML=head('Electrocardiogram report',esc(o.test),btn('Back',"navTo('Electrocardiogram')")+' '+btn('Print / Save PDF','window.print()',true))+renderLabReport(o,patient(o.patient),{logo:'__KNOX_LOGO_DATA__'})+(o.attachments?.length?'<div class="noprint">'+attachmentLinks(o)+'</div>':'');};

const ecgEntryTable=resultEntryTable;resultEntryTable=function(o){if(o.testId!=='ECG12')return ecgEntryTable(o);return '<div class="full result-scroll"><table class="entrytable"><thead><tr><th>Finding / measurement</th><th>Result / status</th><th>Units</th><th>Flag</th></tr></thead><tbody>'+o.template.fields.map((f,i)=>{const r=o.resultRows?.[i]||{};return '<tr><td><b>'+esc(f.name)+'</b></td><td>'+resultInput(f,i,r.value||'')+selectAt('state_'+i,['Result','Not performed','Not applicable'],r.state||'Result','Reporting status for '+f.name)+'</td><td>'+inputAt('unit_'+i,r.unit??f.unit,'Units for '+f.name)+'</td><td>'+selectAt('flag_'+i,['','Abnormal','Critical'],r.flag||'','Manual flag for '+f.name)+'</td></tr>'}).join('')+'</tbody></table></div>'};
