// The server checks the same permissions on every write. Local checks improve usability.
const permitted = key => !!currentUser && can(currentUser,key);
function financeQuickView(){
 if(!canViewSales(currentUser))return '';
 return '<section class="card spacer" id="financeQuickView"><div class="cardhead"><div><h2>Finance at a glance</h2><p class="help" data-finance-summary-status>Loading totals for all saved sales…</p></div>'+btn('View finance',"navTo('Finance')")+'</div><div class="stats padded" style="margin:0">'+[['week','Paid this week'],['month','Paid this month'],['year','Paid this year'],['pending','Outstanding payments']].map(([key,label])=>'<div class="card padded finance-quick-stat"><div class="statlabel">'+label+'</div><strong data-finance-total="'+key+'" style="font-size:24px;display:block;margin-top:8px">—</strong></div>').join('')+'</div></section>';
}
function refreshFinanceQuickView(finance,status){
 const host=document.getElementById('financeQuickView');if(!host||!canViewSales(currentUser))return;
 if(finance)for(const key of ['week','month','year','pending'])host.querySelector('[data-finance-total="'+key+'"]').textContent=money(Number(finance[key]||0));
 host.querySelector('[data-finance-summary-status]').textContent=status;
}
staffForm=function(encoded){
 if(currentUser?.role!=='admin')return notify('Administrator access required.');
 const s=staffCache.find(x=>x.email===decodeURIComponent(encoded||''));
 const selected=s?.permissions||DEFAULT_PERMISSIONS[s?.role||'viewer'];
 modal(s?'Edit staff access':'Create staff login',field('name','Staff name','text',true,s?.name||'')+field('email','Sign-in email','email',true,s?.email||'')+field('position','Position / job title','text',true,s?.position||'')+field('password',s?'New password (leave blank to keep current)':'Password','password',!s)+select('role','Access profile',['viewer','reception','scientist','ceo','admin'])+select('access','Account status',['Active','Disabled'])+'<fieldset class="full" style="border:1px solid #ddd;border-radius:12px;padding:16px"><legend>Allowed activities</legend><p class="help">Select allowed activities. Administrators have full access; active staff can view shared laboratory records.</p>'+Object.entries(PERMISSIONS).map(([key,label])=>'<label style="display:flex;gap:10px;align-items:center;margin:10px 0"><input style="width:18px;height:18px" type="checkbox" name="permission_'+key+'" '+(selected.includes(key)?'checked':'')+'>'+esc(label)+'</label>').join('')+'</fieldset>',async v=>{try{await api('/api/staff','POST',{email:v.email,name:v.name,position:v.position,password:v.password,role:v.role,active:v.access==='Active',permissions:Object.keys(PERMISSIONS).filter(k=>v['permission_'+k])});notify('Staff position and permissions saved');return true}catch(e){notify(e.message);return false}},'Save access');
 const f=document.getElementById('form');if(s){f.elements.email.readOnly=true;f.elements.role.value=s.role;f.elements.access.value=s.active?'Active':'Disabled'}
 f.elements.role.onchange=()=>{for(const key of Object.keys(PERMISSIONS))f.elements['permission_'+key].checked=DEFAULT_PERMISSIONS[f.elements.role.value].includes(key)};
};
loadStaff=async function(){try{const p=await api('/api/staff');staffCache=p.staff;if(page==='Staff accounts')document.getElementById('staffList').innerHTML=table(['Staff / username','Position','Permissions','Status',''],p.staff.map(s=>'<tr><td><b>'+esc(s.name)+'</b><small>'+esc(s.email)+'</small></td><td>'+esc(s.position||s.role)+'</td><td>'+(s.role==='admin'?'Full administrator access':(s.permissions||[]).map(k=>esc(PERMISSIONS[k])).join(', ')||'Read only')+'</td><td>'+badge(s.active?'Active':'Disabled')+'</td><td>'+(s.owner?'Owner':btn('Edit access',"staffForm('"+encodeURIComponent(s.email)+"')"))+'</td></tr>'))}catch(e){if(page==='Staff accounts')document.getElementById('staffList').textContent=e.message}};
const actionPermissions={ultrasoundForm:'ultrasoundEnter',approveUltrasound:'ultrasoundReview',viewUltrasound:'ultrasoundView',deleteUltrasound:'ultrasoundEnter',patientForm:'patients',editPatient:'patients',orderForm:'orders',editOrder:'orders',receive:'specimens',resultForm:'results',amendResult:'amend',qcForm:'qc',saleForm:'finance',orderReceipt:'finance',deleteSale:'delete',deleteRecord:'delete',priceForm:'catalogue',templateForm:'catalogue',customTestForm:'catalogue',interfaceForm:'analyzers',reviewMessage:'importResults'};
for(const [name,key]of Object.entries(actionPermissions)){const previous=window[name];if(typeof previous==='function')window[name]=function(...args){if(!permitted(key)){notify('Permission required: '+PERMISSIONS[key]);return}const output=previous.apply(this,args);if(name==='resultForm'){const action=document.querySelector('#form [name="action"]');if(action&&!permitted('review')){for(const option of [...action.options])if(option.value==='Reviewed')option.remove();action.value='Draft'}}return output}}
const executiveFinancePage=financePage;
financePage=function(){if(canViewSales(currentUser))return executiveFinancePage();if(!permitted('finance'))return head('Finance access restricted','Revenue and sales records are visible only to CEO and administrator accounts.');const seen=new Set(),orders=db.orders.filter(o=>{const key=o.patient+'|'+(o.requestId||o.id);if(seen.has(key))return false;seen.add(key);return true});return head('Receipt desk','Issue individual patient receipts. Revenue summaries and sales histories are restricted.',btn('＋ Record sale','saleForm()',true))+'<section class="card"><div class="cardhead"><h2>Patient order receipts</h2></div>'+table(['Patient','Accession','Receipt'],orders.map(o=>'<tr><td>'+esc(patient(o.patient)?.name)+'</td><td>'+esc(displayNumber(o))+'</td><td>'+btn('View / issue receipt',"orderReceipt('"+o.id+"')")+'</td></tr>'),'No loaded patient orders.')+'</section>'};
const executiveExportSales=exportSales;
exportSales=function(){if(!canViewSales(currentUser))return notify('Sales exports are restricted to CEO and administrator accounts.');return executiveExportSales()};
function clearRestrictedSales(){if(!currentUser||canViewSales(currentUser))return;const pendingIds=new Set((typeof offlinePending!=='undefined'&&(offlinePending||unsaved)&&typeof offlineBase!=='undefined'&&offlineBase?db.sales.filter(s=>!offlineBase.sales.some(old=>old.id===s.id)):[]).map(s=>s.id));for(const data of [db,typeof offlineBase==='undefined'?null:offlineBase,typeof offlineWorking==='undefined'?null:offlineWorking,typeof recordServerBase==='undefined'?null:recordServerBase])if(data){data.sales=(data.sales||[]).filter(s=>pendingIds.has(s.id));data.activity=(data.activity||[]).filter(a=>!/(sale|revenue|receipt|invoice|payment|finance)/i.test(a.text||''));}if(typeof recordTotals!=='undefined'&&recordTotals){delete recordTotals.finance;if(recordTotals.counts)delete recordTotals.counts.sales;}}
const permissionRender=render;
render=function(){clearRestrictedSales();permissionRender();if(!currentUser)return;
 document.querySelectorAll('#nav button').forEach(b=>{const p=b.dataset.page;if(p==='Finance'){b.hidden=!canViewSales(currentUser)&&!permitted('finance');if(!canViewSales(currentUser)){const label=b.querySelector('span');if(label)label.textContent='Receipts';}}if(p==='Audit log')b.hidden=currentUser.role!=='admin';if(p==='Manage records')b.hidden=!['patients','orders','amend','delete'].some(k=>permitted(k));if(p==='Staff accounts')b.hidden=currentUser.role!=='admin'});
 document.querySelectorAll('#app button[onclick]').forEach(b=>{const call=b.getAttribute('onclick').match(/^\s*(\w+)\(/)?.[1],key=actionPermissions[call];if(key){b.disabled=!permitted(key);if(b.disabled)b.title='Permission required: '+PERMISSIONS[key]}});
 if(page==='Overview'&&isFinanceStaff(currentUser))document.querySelectorAll('#app button[onclick]').forEach(b=>{const call=b.getAttribute('onclick').match(/^\s*(\w+)\(/)?.[1];if(['receive','resultForm','showReport','amendResult'].includes(call)){b.disabled=true;b.removeAttribute('onclick');b.title='Finance staff can view order status. Laboratory actions are restricted.'}});
 if(page==='Staff accounts')document.querySelector('#app .help')?.replaceChildren(document.createTextNode('Administrators assign positions and individual activities. Changes are checked on the next online request. Offline devices receive updated access when they reconnect.'));
 if(page==='Settings'){document.getElementById('app').insertAdjacentHTML('beforeend','<section class="card padded spacer"><h2>Your assigned activities</h2><p>'+esc(currentUser.position||currentUser.role)+'</p><p>'+esc(currentUser.role==='admin'?'Full administrator access':permissionsFor(currentUser).map(k=>PERMISSIONS[k]).join(' · ')||'Read-only access')+'</p>'+(currentUser.role==='admin'?btn('Manage staff and permissions',"navTo('Staff accounts')",true):'')+'</section>')}
};

const permissionReload=reloadShared;
reloadShared=async function(){if(navigator.onLine&&currentUser){try{currentUser=(await api('/api/me')).user}catch(error){notify(error.message);return}}return permissionReload()};
