pages.push('Stock Records');
let stockItems=[],stockSequence=0,stockMappingIndex=0;
const stockNumber=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:6});
const stockTests=()=>[...CATALOG,...(db.customTests||[])].filter((t,i,a)=>a.findIndex(x=>x.id===t.id)===i).sort((a,b)=>a.name.localeCompare(b.name));
function stockPage(){return head('Stock Records','Track quantities received, test usage and the stock remaining.',can(currentUser,'stockManage')?btn('＋ Add stock item','stockItemForm()',true):'')+'<section class="card padded"><p class="help">Enter actual quantities with Restock. Link supplies to tests to deduct usage automatically.</p><details><summary>Stock counting help</summary><p class="help">Count kits as individual tests; enter liquids in mL. Configure the quantity used per test. Usage is deducted once when results are first saved, including drafts; earlier results are excluded. Use adjustments for wastage or stock reconciliation.</p></details></section><section class="card spacer"><div class="cardhead"><h2>Items and balances</h2>'+btn('Refresh','loadStock()')+'</div><div class="toolbar"><select id="stockCategory" aria-label="Stock category" onchange="renderStockRows()"><option value="">All supplies</option><option>Rapid tests &amp; strips</option><option>Chemistry reagents</option><option>Hematology &amp; blood bank</option><option>Specimen collection</option><option>Microscopy &amp; culture</option><option>General consumables</option><option>Ultrasound supplies</option><option>Custom supplies</option></select><input id="stockSearch" aria-label="Search stock items" placeholder="Search item name or unit" oninput="renderStockRows()"></div><div id="stockRows" aria-live="polite" class="padded">Loading stock records…</div></section>'}
async function loadStock(){const seq=++stockSequence,session=workspaceSession;try{const data=await api('/api/stocks');if(seq!==stockSequence||session!==workspaceSession||page!=='Stock Records'||!currentUser)return;stockItems=data.items;renderStockRows();if(data.hasMore)document.getElementById('stockRows').insertAdjacentHTML('beforeend','<p class="help">Showing the first 1,000 items.</p>')}catch(e){if(seq===stockSequence&&page==='Stock Records'&&currentUser)document.getElementById('stockRows').innerHTML='<p>'+esc(e.message)+'</p>'+btn('Retry','loadStock()')}}
function renderStockRows(){const host=document.getElementById('stockRows');if(!host)return;const labels=new Map(stockTests().map(t=>[t.id,t.name]));const query=(document.getElementById('stockSearch')?.value||'').toLowerCase(),category=document.getElementById('stockCategory')?.value||'',items=stockItems.filter(i=>(!category||i.category===category)&&(i.name+' '+i.unit).toLowerCase().includes(query));host.innerHTML=table(['Item / unit','Received','Used by tests','Adjustments','Remaining','Test usage','Actions'],items.map(i=>'<tr><td><b>'+esc(i.name)+'</b><small>'+esc(i.category||'Custom supplies')+'</small><small>'+esc(i.unit)+(i.active?'':' · Paused')+'</small><small>Low-stock level: '+stockNumber(i.minimum)+'</small></td><td>'+stockNumber(i.received)+'</td><td>'+stockNumber(i.used)+'</td><td>'+stockNumber(i.adjusted)+'</td><td><b>'+stockNumber(i.balance)+'</b><small>'+(!i.active?'Paused':i.balance<0?'Stock shortage':i.balance===0?'Out of stock':i.balance<=i.minimum?'Low stock':'Available')+'</small></td><td>'+i.links.map(l=>'<small>'+esc(labels.get(l.testId)||l.testId)+' · '+stockNumber(l.perTest)+' '+esc(i.unit)+'/test</small>').join('')+(i.links.length?'':'<small>No test linked</small>')+'</td><td>'+btn('History',"stockHistory('"+i.id+"')")+(can(currentUser,'stockManage')?' '+btn('Restock',"stockMovementForm('"+i.id+"','restock')")+' '+btn('Adjust',"stockMovementForm('"+i.id+"','adjustment')")+' '+btn('Edit',"stockItemForm('"+i.id+"')"):'')+'</td></tr>'),'No stock items found. Add an item to begin.')}
function stockMappingRow(link={}){const n=stockMappingIndex++;const tests=stockTests();if(link.testId&&!tests.some(t=>t.id===link.testId))tests.unshift({id:link.testId,name:link.testId+' (saved test)'});return '<div class="stock-mapping" data-stock-mapping="'+n+'" style="display:grid;grid-template-columns:minmax(0,2fr) minmax(0,1fr) auto;gap:10px;align-items:end;margin-top:12px">'+select('stock_test_'+n,'Test',[['','Choose test'],...tests.map(t=>[t.id,t.name])])+field('stock_usage_'+n,'Quantity per test','number',false,link.perTest??'')+'<button class="btn" type="button" onclick="this.closest(\'.stock-mapping\').remove()" aria-label="Remove test usage">×</button></div>'}
function addStockMapping(link={}){document.getElementById('stockMappings').insertAdjacentHTML('beforeend',stockMappingRow(link));const row=document.getElementById('stockMappings').lastElementChild;if(link.testId)row.querySelector('select').value=link.testId;row.querySelector('input').step='0.000001';row.querySelector('input').min='0.000001'}
function stockItemForm(itemId){if(!can(currentUser,'stockManage'))return notify('Stock management permission required.');if(!navigator.onLine)return notify('Connect to manage shared stock records.');const item=stockItems.find(i=>i.id===itemId),id=item?.id||crypto.randomUUID();stockMappingIndex=0;
 modal(item?'Edit stock item':'Add stock item',field('name','Item name','text',true,item?.name||'')+field('unit','Stock unit (e.g. mL, pieces, tests)','text',true,item?.unit||'')+(!item?field('opening','Opening quantity','number',true,0):'')+field('minimum','Low-stock level','number',true,item?.minimum||0)+(item?select('active','Automatic deductions',['Active','Paused']):'')+'<section class="full"><h3>Quantity used per test</h3><p class="help">Enter the quantity used per whole test in the stock unit above. Changes apply to future results.</p><div id="stockMappings"></div><button class="btn" type="button" onclick="addStockMapping()">＋ Link a test</button></section>',async v=>{const links=[...document.querySelectorAll('[data-stock-mapping]')].map(row=>{const n=row.dataset.stockMapping;return {testId:v['stock_test_'+n],perTest:v['stock_usage_'+n]}});if(links.some(l=>!l.testId||!l.perTest))return notify('Choose a test and quantity for every usage row.'),false;await api('/api/stocks/items','POST',{id,name:v.name,unit:v.unit,minimum:v.minimum,opening:v.opening||0,links,...(item?{version:item.version,active:v.active==='Active'}:{})});notify('Stock item saved');return true},'Save stock item');
 const f=document.getElementById('form');for(const name of ['opening','minimum'])if(f.elements[name]){f.elements[name].step='0.000001';f.elements[name].min='0'}if(item){f.elements.unit.readOnly=true;f.elements.active.value=item.active?'Active':'Paused'}for(const l of item?.links||[])addStockMapping(l);
}
function stockMovementForm(itemId,kind){if(!can(currentUser,'stockManage'))return notify('Stock management permission required.');if(!navigator.onLine)return notify('Connect to update shared stock records.');const item=stockItems.find(i=>i.id===itemId);if(!item)return;const id=crypto.randomUUID();modal(kind==='restock'?'Restock · '+item.name:'Adjust · '+item.name, '<p class="help full">Current remaining: '+stockNumber(item.balance)+' '+esc(item.unit)+'. '+(kind==='restock'?'Enter the quantity received.':'Enter a positive quantity to add stock or a negative quantity for wastage, expiry or repeat runs.')+'</p>'+field('quantity','Quantity ('+item.unit+')','number',true)+field('reason',kind==='restock'?'Delivery / supplier reference':'Adjustment reason','text',true),async v=>{await api('/api/stocks/movements','POST',{id,itemId,kind,quantity:v.quantity,reason:v.reason});notify(kind==='restock'?'Delivery added to stock':'Stock adjustment saved');return true},kind==='restock'?'Add delivery':'Save adjustment');document.querySelector('#form [name="quantity"]').step='0.000001';if(kind==='restock')document.querySelector('#form [name="quantity"]').min='0.000001'}
async function stockHistory(itemId){const session=workspaceSession;try{const data=await api('/api/stocks?'+new URLSearchParams({itemId}));if(session!==workspaceSession||page!=='Stock Records'||!currentUser)return;const item=stockItems.find(i=>i.id===itemId);modal('Stock history · '+(item?.name||''),'<section class="full"><p class="help">Latest 100 entries · GMT.</p>'+table(['Time','Movement','Quantity','Order / test','Reason','Recorded by'],data.history.map(m=>'<tr><td>'+esc(m.created.replace('T',' ').slice(0,19))+'</td><td>'+esc(m.kind)+'</td><td>'+stockNumber(m.quantity)+'</td><td>'+esc(m.order_id||'—')+'<small>'+esc(m.test_id||'')+'</small></td><td>'+esc(m.reason)+'</td><td>'+esc(m.actor)+'</td></tr>'),'No movements.')+'</section>',()=>true,'Close');makeWide()}catch(e){notify(e.message)}}
const stockRender=render;
render=function(){stockRender();if(!currentUser)return;document.querySelectorAll('#nav button').forEach(b=>{if(b.dataset.page==='Stock Records')b.hidden=!can(currentUser,'stockView')});if(page==='Stock Records'){if(!can(currentUser,'stockView')){document.getElementById('app').innerHTML=head('Stock Records','Stock viewing permission required.');return}document.getElementById('app').innerHTML=stockPage();void loadStock()}};
const stockSignOut=manualSignOut;manualSignOut=function(){stockSequence++;stockItems=[];stockSignOut()};
