pages.push('Ultrasound');
const ultrasoundAllowed=key=>!!currentUser&&can(currentUser,key);
function ultrasoundTemplates(){return tests().filter(t=>t.department==='Ultrasound')}
function ultrasoundPage(){
 if(!ultrasoundAllowed('ultrasoundView'))return head('Ultrasound','Ask an administrator for ultrasound access.');
 const rows=db.ultrasoundReports.filter(r=>matches((patient(r.patient)?.name||'')+' '+r.test+' '+displayNumber(r))).map(r=>'<tr><td><b>'+esc(patient(r.patient)?.name)+'</b><small>Patient ID '+esc(patientNumber(r.patient))+'</small></td><td>'+esc(r.test)+'<small>Scan '+esc(displayNumber(r))+'</small></td><td>'+esc(r.examAt?.replace('T',' ').replace('.000Z',' GMT')||'Not recorded')+'</td><td>'+badge(r.reviewed?(r.amendments?.length?'Amended':'Final'):'Draft')+'</td><td>'+(r.reviewed?btn('View / print',"viewUltrasound('"+r.id+"')")+(ultrasoundAllowed('ultrasoundAmend')&&ultrasoundAllowed('ultrasoundEnter')&&ultrasoundAllowed('ultrasoundReview')?' '+btn('Amend',"ultrasoundForm('"+r.id+"')"):''):(ultrasoundAllowed('ultrasoundEnter')?btn('Edit draft',"ultrasoundForm('"+r.id+"')"):'')+(ultrasoundAllowed('ultrasoundReview')?' '+btn('Approve',"approveUltrasound('"+r.id+"')"):'')+(ultrasoundAllowed('ultrasoundEnter')&&can(currentUser,'delete')?' '+btn('Delete draft',"deleteUltrasound('"+r.id+"')"):'') )+'</td></tr>');
 return head('Ultrasound','Dedicated imaging reports · examination times in GMT',ultrasoundAllowed('ultrasoundEnter')?btn('＋ New ultrasound report','ultrasoundForm()',true):'')+'<section class="card">'+toolbar('Search patient, scan or report number')+table(['Patient','Examination / scan','Exam time','Status','Actions'],rows,'No ultrasound reports on this page.')+'</section><section class="card padded spacer"><h2>Scan report templates</h2><div class="testpicker">'+ultrasoundTemplates().map(t=>'<div class="padded"><b>'+esc(t.name)+'</b><small class="muted">'+templateFields(t).length+' structured finding fields</small>'+(ultrasoundAllowed('ultrasoundEnter')?btn('Use template',"ultrasoundForm(null,'"+t.id+"')"):'')+'</div>').join('')+'</div></section><section class="card padded spacer"><h2>Your ultrasound privileges</h2><p>'+['ultrasoundView','ultrasoundEnter','ultrasoundReview','ultrasoundAmend'].filter(k=>ultrasoundAllowed(k)).map(k=>esc(PERMISSIONS[k])).join(' · ')+'</p><p class="help">Manage access under Staff.</p></section>';
}
function ultrasoundForm(id=null,templateId=null){
 if(!ultrasoundAllowed('ultrasoundView')||!ultrasoundAllowed('ultrasoundEnter'))return notify('Ultrasound entry permission required.');
 const old=id?db.ultrasoundReports.find(r=>r.id===id):null;
 if(old?.reviewed&&(!ultrasoundAllowed('ultrasoundAmend')||!ultrasoundAllowed('ultrasoundReview')))return notify('Ultrasound amendment and approval permissions are required.');
 if(!db.patients.length){notify('Register a patient first.');return}
 if(!old?.template&&!templateId){modal('Choose ultrasound report template',select('templateId','Examination',ultrasoundTemplates().map(t=>[t.id,t.name])),v=>{closeModal();ultrasoundForm(id,v.templateId);return false},'Continue');return}
 const t=old?.template||snapshot(testById(templateId)),template=old?.template||{...t,fields:t.fields.filter(f=>!/^Impression|^Clinical indication|^Assessment category/i.test(f.name))},rows=old?.resultRows||template.fields.map(f=>({...f,value:'',state:'Result'}));
 const textArea=(name,label,value='')=>'<label class="full">'+esc(label)+'<textarea name="'+name+'" rows="3" maxlength="6000">'+esc(value)+'</textarea></label>';
 modal(old?.reviewed?'Amend ultrasound report':'Ultrasound · '+t.name,select('patient','Patient',db.patients.map(p=>[p.id,p.name+' · '+displayNumber(p)]))+'<div class="full"><label>Search all registered patients<input id="ultrasoundPatientSearch" placeholder="Name starts with or exact patient ID"></label><button type="button" class="btn" onclick="searchOrderPatients(document.getElementById(\'ultrasoundPatientSearch\').value)">Find patient</button></div>'+field('examAt','Examination date / time (GMT)','datetime-local',true,(old?.examAt||new Date().toISOString()).slice(0,16))+field('clinician','Referring clinician','text',false,old?.clinician||'')+field('operator','Sonographer / performing clinician','text',true,old?.operator||currentUser.name)+field('equipment','Equipment / probe','text',false,old?.equipment||'')+field('technique','Technique / approach','text',false,old?.technique||'')+textArea('indication','Clinical indication',old?.indication)+'<div class="full result-scroll"><table class="entrytable"><thead><tr><th>Finding / measurement</th><th>Entry</th><th>Reporting status</th></tr></thead><tbody>'+template.fields.map((f,i)=>'<tr><td><b>'+esc(f.name)+'</b><small>'+esc(f.unit||'')+'</small></td><td>'+resultInput(f,i,rows[i]?.value||'')+'</td><td>'+selectAt('state_'+i,['Result','Not assessed','Not applicable'],rows[i]?.state||'Result',f.name+' status')+'</td></tr>').join('')+'</tbody></table></div>'+textArea('impression','Impression',old?.impression)+textArea('recommendation','Recommendations / follow-up',old?.recommendation)+(old?.reviewed?textArea('amendmentReason','Reason for amendment (required)')+'<label class="full checkline"><input name="identityVerified" type="checkbox" required> I have verified patient identity and reviewed the findings and impression.</label>':'<p class="help full">Save a draft for approval. Mark unassessed structures explicitly.</p>'),async v=>{
  if(old?.reviewed&&!navigator.onLine){notify('Connect before amending a final ultrasound report.');return false}
  const record={...old,id:old?.id||uid('US'),patient:v.patient,name:(patient(v.patient)?.name||'')+' · '+t.name,testId:t.id,test:t.name,department:'Ultrasound',template,created:old?.created||new Date().toISOString(),examAt:new Date(v.examAt+':00Z').toISOString(),clinician:v.clinician,operator:v.operator,equipment:v.equipment,technique:v.technique,indication:v.indication,resultRows:template.fields.map((f,i)=>({...f,value:v['v_'+i]||'',state:v['state_'+i]})),impression:v.impression,recommendation:v.recommendation,reviewed:!!old?.reviewed,identityVerified:!!v.identityVerified,amendmentReason:v.amendmentReason||''};
  if(old)db.ultrasoundReports=db.ultrasoundReports.map(r=>r.id===old.id?record:r);else db.ultrasoundReports.unshift(record);
  log('Ultrasound '+(old?.reviewed?'amended':'draft saved')+': '+t.name);return save(old?.reviewed?'Ultrasound report amended':'Ultrasound draft saved');
 },old?.reviewed?'Save final amendment':'Save draft');makeWide();if(old)document.querySelector('#form [name="patient"]').value=old.patient;
}
async function ultrasoundSignature(file){
 if(!file)return null;if(!['image/png','image/jpeg'].includes(file.type)||file.size>2000000)throw new Error('Choose a PNG or JPEG signature smaller than 2 MB.');
 const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=350;canvas.height=90;const scale=Math.min(350/bitmap.width,90/bitmap.height);canvas.getContext('2d').drawImage(bitmap,0,0,bitmap.width*scale,bitmap.height*scale);bitmap.close();return canvas.toDataURL('image/png');
}
function approveUltrasound(id){
 if(!ultrasoundAllowed('ultrasoundView')||!ultrasoundAllowed('ultrasoundReview'))return notify('Ultrasound approval permission required.');if(!navigator.onLine)return notify('Connect to approve an ultrasound report.');const r=db.ultrasoundReports.find(r=>r.id===id);if(!r||r.reviewed)return;
 modal('Approve ultrasound report','<p class="full"><b>'+esc(patient(r.patient)?.name)+'</b> · '+esc(r.test)+'</p><div class="full">'+r.resultRows.map(row=>'<p><b>'+esc(row.name)+':</b> '+esc(row.state==='Result'?row.value:row.state)+'</p>').join('')+'<p><b>Impression:</b> '+esc(r.impression)+'</p></div><label class="full checkline"><input type="checkbox" name="verified" required> I have verified patient identity and reviewed the scan findings and impression.</label><label class="full">Approver signature (optional)<input id="ultrasoundSignatureUpload" type="file" accept="image/png,image/jpeg"><small>PNG or JPEG, up to 2 MB.</small></label>',async v=>{const signature=await ultrasoundSignature(document.getElementById('ultrasoundSignatureUpload').files[0]);const prior={...r};Object.assign(r,{reviewed:true,identityVerified:!!v.verified,signature});const ok=await save('Ultrasound report approved');if(!ok)Object.assign(r,prior);return ok},'Approve final report');makeWide();
}
function viewUltrasound(id){if(!ultrasoundAllowed('ultrasoundView'))return notify('Ultrasound view permission required.');if(unsaved)return notify('Save or reload before printing.');const r=db.ultrasoundReports.find(r=>r.id===id);if(!r?.reviewed)return notify('Only final ultrasound reports can be printed.');document.getElementById('app').innerHTML=head('Ultrasound report',esc(r.test),btn('Print / Save PDF','window.print()',true)+' '+btn('Back to ultrasound',"navTo('Ultrasound')"))+'<p class="help noprint">Turn off Headers and footers in browser print settings to omit the website address.</p>'+renderUltrasoundReport(r,patient(r.patient),{logo:'__KNOX_LOGO_DATA__'});}
async function deleteUltrasound(id){if(!ultrasoundAllowed('ultrasoundView')||!ultrasoundAllowed('ultrasoundEnter')||!can(currentUser,'delete'))return notify('Ultrasound entry and deletion privileges required.');const r=db.ultrasoundReports.find(r=>r.id===id);if(!r||r.reviewed)return notify('Final reports must be amended.');if(!confirm('Delete this ultrasound draft?'))return;db.ultrasoundReports=db.ultrasoundReports.filter(r=>r.id!==id);await save('Ultrasound draft deleted');}
const ultrasoundRender=render;
render=function(){ultrasoundRender();if(!currentUser)return;document.querySelectorAll('#nav button').forEach(b=>{if(b.dataset.page==='Ultrasound')b.hidden=!ultrasoundAllowed('ultrasoundView')});if(page==='Ultrasound')document.getElementById('app').innerHTML=ultrasoundPage();};
